### ISSUE TITLE
please enable nvenc support and libvlc.so is not found

### ISSUE THREAD

**Issue by omen23** [snapcrafters/obs-studio#10]
the ffmpeg snap is compiled with nvenc and cuda support - so should the snap of obs be but because this runs in a virtual filesystem obs wont find an existing VLC installation.

error: os_dlopen(libvlc.so.5->libvlc.so.5): libvlc.so.5: cannot open shared object file: No such file or directory

**Comment by thomasfinstad** [comment]
I too would love to use vlc media source with the snap. The nvenc work great for me when ffmpeg and obs are both running from snap packages.

**Comment by dmerrick** [comment]
Bumping this thread to say I'd also really like support for the VLC plugin

(NVENC works fine for me, thanks!)

**Comment by flexiondotorg** [comment]
nvenc and VLC plugins have been working for some time now.
