### ISSUE TITLE
V4l2 output missing (again)

### ISSUE THREAD

**Issue by janakelarsson** [snapcrafters/obs-studio#101]
This worked before the holidays, now no entry in the Tools menu, using
obs-studio              26.1.0                      1185   latest/stable    snapcrafters  -
v4l2loopback kernel module still loaded

**Comment by Alex-INtegrator** [comment]
Same problem for me.

**Comment by janakelarsson** [comment]
There is no v4l2sink in /snap/obs-studio/

**Comment by janakelarsson** [comment]
Not in the --edge release (1191) either.

**Comment by janakelarsson** [comment]
This now works for me, note that the UI has changed. The virtual cam has moved from the "Tools" menu into the control buttons at the bottom right in the UI. The button is called "Start Virtual Camera". You may need to restart Zoom after starting the virtual camera.

I performed "sudo snap connect obs-studio:kernel-module-observe" as instructed, I do not know if this helped or not. Perhaps I only needed to start the virtual cam from the UI. 

Apparently this is now built-in, and does not require the v4l2sink plugin anymore. It is unclear to me precisely how the device number is chosen, but it now works.

I'll close the issue in a few days, just so others can read this.
