### ISSUE TITLE
Virtual camera causes 'Segmentation fault'

### ISSUE THREAD

**Issue by stijnghesquiere** [snapcrafters/obs-studio#104]
After update to the latest snap version: 
obs-studio          26.1.2-35-gbb6b1e53f        1195   latest/stable    snapcrafters  -

OBS-studio crashes when the virtual camera is activated. 
Gives: 
info: Virtual camera started
Segmentation fault

26.1.2 snap version 1194 worked, new not.

**Comment by stijnghesquiere** [comment]
Actually, why is stable, candidate, beta and edge always updated at once with this snap? Wouldn't it make more sense to first update in candidate or edge? Now I always have the revert back to a previous version if it breaks again. I'm really dreading OBS-studio updates, as it did break a lot of times in the past year. I'm not blaming anyone, bugs can happen, but I would like to advocate some prudence before throwing them in 'stable. 
But if I'm wrong, or missed something, please educate me!

**Comment by cash-flagg** [comment]
I have the same issue with this version, waiting for an update that brings this feature back like the previous release.

**Comment by flexiondotorg** [comment]
I've uploaded a new revision (1198) of the snap (26.1.2-197-g81a89e689) to the edge channel, which should resolve this issue. Please test it and report back.

    snap refresh obs-studio --edge

**Comment by cash-flagg** [comment]
This edge version has the Virtual Camera function working again for me. Thanks!

**Comment by stijnghesquiere** [comment]
Virtual camera works again on obs-studio (edge) 26.1.2-197-g81a89e689! 
Thanks!
