### ISSUE TITLE
GStreamer v4l2src unavailable in 26.1.2

### ISSUE THREAD

**Issue by eugenios** [snapcrafters/obs-studio#106]
Ubuntu box, 20.10. Gstreamer is installed, and gst-launch-1.0 -v v4l2src ! <whatever sink> works.
OBS studio works, reads from webcam (V4L2 source), lets me add a Gstreamer source. "videotestsrc" as source works perfectly.
But setting ANY pipeline in OBS that start with v4l2src gives in the log:

`error: Cannot start GStreamer: no element "v4l2src"`

Enabling detailed GST_DEBUG, it gives me:

`GST_ELEMENT_FACTORY gstelementfactory.c:456gst_element_factory_make: no such element factory "v4l2src"!`

Useful info: snap lib dir for plugins (/snap/obs-studio/1195/usr/lib/x86_64-linux-gnu/gstreamer-1.0/) does NOT contain libgstvideo4linux.so. This module is only in /usr/lib/x86_64-linux-gnu/gstreamer-1.0/

**Comment by flexiondotorg** [comment]
I've uploaded a new revision (1198) of the snap (26.1.2-197-g81a89e689) to the edge channel, which should resolve this issue. Please test it and report back.

    snap refresh obs-studio --edge

**Comment by eugenios** [comment]
> I've uploaded a new revision (1198) of the snap (26.1.2-197-g81a89e689) to the edge channel, which should resolve this issue. Please test it and report back.
> 
> ```
> snap refresh obs-studio --edge
> ```

That worked at the first shot! Super!
I can confirm the issue is resolved.
