### ISSUE TITLE
gphoto input not showing

### ISSUE THREAD

**Issue by KnutssonDevelopment** [snapcrafters/obs-studio#107]
The gphoto plugin does not seem to be loading in Ubuntu 20.04.

info: ---------------------------------
info:   Loaded Modules:
info:     vlc-video.so
info:     transition-table.so
info:     time-warp-scan.so
info:     text-freetype2.so
info:     spectralizer.so
info:     source-switcher.so
info:     sndio.so
info:     rtmp-services.so
info:     replay-source.so
info:     recursion-effect.so
info:     obs-x264.so
info:     obs-websocket.so
info:     obs-vst.so
info:     obs-vnc.so
info:     obs-transitions.so
info:     obs-rtspserver.so
info:     obs-rgb-levels-filter.so
info:     obs-outputs.so
info:     obs-ndi.so
info:     obs-libfdk.so
info:     obs-gstreamer.so
info:     obs-filters.so
info:     obs-ffmpeg.so
info:     obs-browser.so
info:     obs-audio-pan-filter.so
info:     move-transition.so
info:     linux-v4l2.so
info:     linux-pulseaudio.so
info:     linux-jack.so
info:     linux-decklink.so
info:     linux-capture.so
info:     linux-alsa.so
info:     libtext-pango.so
info:     image-source.so
info:     gradient-source.so
info:     frontend-tools.so
info:     freeze-filter.so
info:     dynamic-delay.so
info:     dvd-screensaver.so
info:     dir-watch-media.so
info:     decklink-ouput-ui.so
info:     decklink-captions.so
info:     advanced-scene-switcher.so
info:     StreamFX.so
info: ---------------------------------

**Comment by KristijanZic** [comment]
I can confirm this issue on Ubuntu 20.04 Wayland. Can't test under X11 as obs-studio currently doesn't launch in that session as per #99 .

**Comment by flexiondotorg** [comment]
Closing this as I can not reproduce it. My logs clearly show the gPhoto plugin is being loaded and I have "gPhoto live preview capture" in my available input when adding a new source.
