### ISSUE TITLE
Add libwidevine (or support for user-provided libwidevine) in the Browser source

### ISSUE THREAD

**Issue by EssGeeEich** [snapcrafters/obs-studio#109]
See title.
libwidevine addition (or support) would be a great addition.
It'll let spotify play music from within OBS without resorting to using Desktop audio, which lets you also remove it from Twitch VODs.

The required files should be `libwidevinecdm.so` and `libwidevinecdmadapter.so` and they ...should... go in `/usr/lib64/chromium-plugins`. _(SOURCES NEEDED)_

**Comment by flexiondotorg** [comment]
Sorry, a license is (required which we don't have) to distribute the proprietary Windevine modules.

**Comment by EssGeeEich** [comment]
I understand perfectly that a license is required - which is why I'm also proposing a very basic support for an user-provided module.

No redistribution, just let an user insert his own libwidevines in, say, `~/snap/obs-studio/something` and have CEF load it.

If there's already a way to do this with snaps, please excuse this thread, but I haven't found a way to do so.
