### ISSUE TITLE
Desktop Audio not produce any noise in audio mixer

### ISSUE THREAD

**Issue by d9nchik** [snapcrafters/obs-studio#111]
**Describe the bug**
Desktop audio in audio mixer does not recognize any sounds

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Audio mixer'
2. Mute mic/aux
3. Unmute desktop audio
4. Open any video from youtube with sound
5. See that desktop audio does not notice any sounds

**Expected behaviour**
I want to have the ability to record audio from a PC without a full time turned microphone. Also, the quality of PC sounds after coming through micro is terrible.

**Screenshots**
![bug](https://user-images.githubusercontent.com/54186666/110973045-6424c900-8365-11eb-94f1-cd36b8921277.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS
 - OBS: 26.1.2-35-gbb6b1e53f

**Comment by flexiondotorg** [comment]
I can not reproduce this issue. Desktop Audio plays and the quality is good.

**Comment by d9nchik** [comment]
I think the problem is that I have integrated an audio card. That's why OBS can not differentiate them. Similar problem I found at [this link](https://obsproject.com/forum/threads/desktop-audio-does-not-work-in-ubuntu.108017/), but I haven't external USB micro to test. Also, the problem reproduces for the OBS version installed from the command line via ```sudo apt install```.

**Comment by flexiondotorg** [comment]
Have you connected the `audio-record` interface?

    snap connect obs-studio:audio-record

**Comment by d9nchik** [comment]
I have tried `snap connect obs-studio:audio-record`. Symptoms are the same.

**Comment by flexiondotorg** [comment]
Sorry, I am unable to reproduce this issue.

**Comment by flexiondotorg** [comment]
Have you selected the correct audio device in the OBS Settings?

**Comment by d9nchik** [comment]
I've selected the correct audio device.

**Comment by flexiondotorg** [comment]
Are you sure? The only way I can recreate this issue is if I select the wrong audio device or sink.
