### ISSUE TITLE
How install virtual caméra oBS

### ISSUE THREAD

**Issue by Jonathanr67** [snapcrafters/obs-studio#113]
Need help for install virtual camera on obs 26.1.2-35 gbb6b 1e53f 64 bit on ubuntu 20.04 lts

I try this with no success in terminal :

sudo snap connect obs-studio:kernel-module-observe sudo apt -y install v4l2loopback-dkms v4l2loopback-utils echo "options v4l2loopback devices=1 video_nr=13 card_label='OBS Virtual Camera' exclusive_caps=1" | sudo tee /etc/modprobe.d/v4l2loopback.conf echo "v4l2loopback" | sudo tee /etc/modules-load.d/v4l2loopback.conf sudo modprobe -r v4l2loopback sudo modprobe v4l2loopback devices=1 video_nr=13 card_label='OBS Virtual Camera' exclusive_caps=1

tee : option invalide -- 'r'
Saisissez « tee --help » pour plus d'informations.
erreur : unknown flag `y'

Do you have any solution. Thank you

**Comment by flexiondotorg** [comment]
Please follow the instructions in the README. Don't paste everything into the terminal in one line. 

Closing this as the issue tracker is for bug reports now technical support :smiley:
