### ISSUE TITLE
Doesn't work with obs-linuxbrowser

### ISSUE THREAD

**Issue by zelikos** [snapcrafters/obs-studio#13]
The obs-linuxbrowser plugin is included with the snap, but trying to add a Linux Browser source causes a segmentation fault; this seems to be an issue only with the snap version, as reported [here](https://github.com/bazukas/obs-linuxbrowser/issues/105#issuecomment-484001636).

**Comment by dmerrick** [comment]
I'm also interested in the linux browser plugin

**Comment by flexiondotorg** [comment]
Fixed via https://github.com/snapcrafters/obs-studio/commit/be1edb9f3dee8c9747431955c218020202894d92
