### ISSUE TITLE
Weird click action in Ubuntu 19.04

### ISSUE THREAD

**Issue by wpbryant** [snapcrafters/obs-studio#14]
Installed snap in Ubuntu 19.04 (thank you by the way this version in all other respects runs better with hardware support than the package file). When running OBS a single mouse click does not select/deselect items as in other programs. Did not have this issue when installing using the main OBS PPA. If you click an item, it doesn't "un-click" and so you have to click twice to select or otherwise you are dragging your click around the screen.

**Comment by flexiondotorg** [comment]
I can not reproduce this. Can you confirm if this is still an issue?
