### ISSUE TITLE
Add Looking Glass plugin

### ISSUE THREAD

**Issue by Josh-MB** [snapcrafters/obs-studio#145]
I'm having an issue similar to #122 , but with a 3rd party plugin rather than opengl. I'm trying to run the [Looking Glass](https://github.com/gnif/LookingGlass) plugin on Manjaro. I've built the plugin from source, and it works fine on the system installed OBS, but when I try to run it in the snap version, it gives me:

`error: os_dlopen(/home/josh/snap/obs-studio/1273/.config/obs-studio/plugins/looking-glass-obs/bin/64bit/liblooking-glass-obs.so->/home/josh/snap/obs-studio/1273/.config/obs-studio/plugins/looking-glass-obs/bin/64bit/liblooking-glass-obs.so): /lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.33' not found (required by /home/josh/snap/obs-studio/1273/.config/obs-studio/plugins/looking-glass-obs/bin/64bit/liblooking-glass-obs.so)`

I'm not really sure what I'm supposed to do with `LD_LIBARY_PATH`/`SNAP_LIBRARY_PATH` mentioned in #122 . I've tried pointing them at `/usr/lib` which is where my `libc.so` seems to be, but that didn't work. I also added a symlink to `/usr/lib/libc.so` in `~/snap/obs-studio/1273/lib/x86_64-linux-gnu` to no avail.

**Comment by Josh-MB** [comment]
I can give it a shot. Haven't used snap much, but I'll look at other similar pull requests and try to get it running

**Comment by Josh-MB** [comment]
I got it running locally, and have submitted a pull request: #149

**Comment by flexiondotorg** [comment]
Fixed via #149
