### ISSUE TITLE
OBS Not Opening

### ISSUE THREAD

**Issue by timtjcb** [snapcrafters/obs-studio#148]
Help. OBS suddenly won't open. I tired reinstalling using the Ubuntu Software (store?) but still wont open. "obs" is showing in the system monitor but not opening.
I can install and open the plain version of OBS in the Ubuntu Software (Store?) but not the modified OBS.
![image](https://user-images.githubusercontent.com/93458410/139564387-ef6c9b49-ce91-47c2-9fbf-e8cf1695d0fb.png)
![image](https://user-images.githubusercontent.com/93458410/139564415-06e24fd1-9f2b-4b66-b9f9-756e5d259e78.png)

**Comment by timtjcb** [comment]
+++Adding+++
I am using Ubuntu 20.04.3 LTS with complete Ubuntu Studio installed.
![image](https://user-images.githubusercontent.com/93458410/139564636-12e1339d-1df2-41a5-8477-8a84e2d50f0b.png)

**Comment by flexiondotorg** [comment]
Please run the OBS snap from a terminal and paste the output here:

    snap run obs-studio

**Comment by Mmalviss** [comment]
I'm having the same issue on Ubuntu 20.04.3 LTS.
Tried re-installing.
Tried running 'snap run obs-studio' in terminal -> no output.
Have to re-open terminal (kill the process) to issue other commands.

I am fairly new to Linux systems fyi

**Comment by flexiondotorg** [comment]
Fixed via #172
