### ISSUE TITLE
[Bug]: files in mp4 format incompatible with discord

### ISSUE THREAD

**Issue by christian66-gif** [snapcrafters/obs-studio#193]
### What happened?

when I try to upload an .mp4 video to discord it tells me an upload error... on my PC the video plays easily... the videos are window captures from the Blender release... I tested with other formats it doesn't work on discord either.

### What should have happened?

my videos created with Blender for example upload without problem  ... my settings OBS Studio ... 
![image](https://github.com/snapcrafters/obs-studio/assets/130861116/78f74d8f-7e7c-49d7-88f0-b77c2125f42c)

![image](https://github.com/snapcrafters/obs-studio/assets/130861116/f1584a52-f542-4e12-b052-ab2ab0dc0ffa)
installed with snap-store ubuntu 22.04.4 LTS

Is there a special setting to make in OBS Studio to be able to upload to Discord... Thank you

**Comment by BrycensRanch** [comment]
not a bug with this software in the first place, fragmented mp4 isn't the type of file format discord wants. this is intended behavior of the application

**Comment by lengau** [comment]
Thanks for this report! Unfortunately, I have a pile of bad news. 

1. I couldn't reproduce this myself even with fragmented MP4s, including the uploading to Discord part. My testing showed that any mp4 file produced from the obs snap on my machine did work in Discord (including the previews), but Discord didn't recognise an mkv file.
2. Whatever's happening here isn't likely related to the obs studio snap, so this would probably need to be reported [upstream](https://github.com/obsproject/obs-studio/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) if it were an obs issue
3. I think @BrycensRanch is probably right that this is something in Discord. You could [file a request to Discord](https://support.discord.com/hc/en-us/community/topics), but I'm not sure they'll answer.

Does this only occur when using NVENC, or does it fail when using software encoding too?

**Comment by christian66-gif** [comment]
Hello... the problem is resolved... it came from the discord
Thanks a lot
