### ISSUE TITLE
Version management isn't working as expected

### ISSUE THREAD

**Issue by popey** [snapcrafters/obs-studio#2]
The obs part does the following

```
last_committed_tag="$(git describe --tags --abbrev=0)"
```

Which results in
```
$ echo $last_committed_tag 
21.1.1
```

But the latest commited tag upstream is 21.1.2. This results in an edge build, and not a stable build of 21.1.2 being done, which isn't what's expected.

**Comment by Lin-Buo-Ren** [comment]
Haven't you considered using the automatically generated version sting by setting the `version` key to `git` ?

**Comment by popey** [comment]
That doesn't work when the snapcraft.yaml isn't in the upstream source tree.

**Comment by flexiondotorg** [comment]
This is fixed.
