### ISSUE TITLE
Add lib loading folder and binary foler in the users home/settings dir

### ISSUE THREAD

**Issue by thomasfinstad** [snapcrafters/obs-studio#20]
There does not currently seem to be any way to load in extra plugins due to them needing libraries not included in the snap.

If possible can you set the snap up to have an extra bin and lib folder in the paths so we can load in plugins to the snap?

You can have a look at the downstream issue I opened in the plugin project: https://github.com/univrsal/input-overlay/issues/93

**Comment by flexiondotorg** [comment]
Fixed via https://github.com/snapcrafters/obs-studio/commit/50d4617b902b8e47414f3210e30bda3d8e3e6b6a
