### ISSUE TITLE
Upgrading Nvidia Drivers to 440.48.02 crash OBS

### ISSUE THREAD

**Issue by luisalvarado** [snapcrafters/obs-studio#23]
On Ubuntu, if you upgrade the Nvidia Drivers to 440.48.02 (which are available since 2 days ago) will crash OBS when you try to started it, stating that:

![image](https://user-images.githubusercontent.com/29236/72614919-15aea280-38f9-11ea-9c34-982effe97d64.png)

This was working properly 15 minutes before the upgrade just in case. The video card is an Nvidia GTX 1080 and I am using Ubuntu 19.10

**Comment by mmtrt** [comment]
Currently snapd doesn't support nv drivers having microversion i.e 440.xx.xx atm so you have to use drivers without microversion like 435.xx and currently this [MR](https://github.com/snapcore/snapd/pull/7942) adds support for this is yet to be reviewed could take time.

**Comment by luisalvarado** [comment]
Thank you @mmtrt it looks like todays driver update fixed the issue. It is the 440.59 version.
