### ISSUE TITLE
Can not stream to Facebook live

### ISSUE THREAD

**Issue by dzkahn** [snapcrafters/obs-studio#25]
It appears that OBS was not compiled with mbed TLS support as stated in the OBS install wiki

Note: as of May 1, 2019, Facebook live now mandates the use of RTMPS. That functionality requires your distro's mbed TLS package, which obs-studio/cmake/Modules/FindMbedTLS.cmake script searches for at compile time.

**Comment by flexiondotorg** [comment]
Fixed via https://github.com/snapcrafters/obs-studio/commit/d89bd09368cf865fabf3af9d3ecc33607a7c84da
