### ISSUE TITLE
Cannot compile using master branch

### ISSUE THREAD

**Issue by ymauray** [snapcrafters/obs-studio#27]
I've tried to build the snap by cloning the master branch, but it failed to compile : 
```
[ 59%] Building C object plugins/obs-filters/CMakeFiles/obs-filters.dir/noise-gate-filter.c.o
/root/parts/obs/src/plugins/obs-outputs/librtmp/rtmp.c: In function ‘b64enc’:
/root/parts/obs/src/plugins/obs-outputs/librtmp/rtmp.c:2547:9: error: unknown type name ‘base64_encodestate’
         base64_encodestate state;
         ^~~~~~~~~~~~~~~~~~
```

I tried on multiple machines, on Ubuntu 18.04 and Ubuntu 19.10, using multipass or lxd. Same result each time.

I am available on telegram (at)FrenchGuyCH if needed.

**Comment by popey** [comment]
Should be fixed by https://github.com/snapcrafters/obs-studio/commit/d89bd09368cf865fabf3af9d3ecc33607a7c84da
