### ISSUE TITLE
“JACK input client source” still not working in obs-studio

### ISSUE THREAD

**Issue by zelyev** [snapcrafters/obs-studio#29]
https://github.com/snapcrafters/obs-studio/issues/26

This issue seems to be not resolved:

Steps I took:

1. I removed the standard obs-studio version
2. I installed the --edge version
3. I checked the possible connections, and Jack1 now really is available
4. I connected Jack1 successfully to obs-studio

However the following "errors" happen:

- Jack-Input-Source is still not available in CARLA or in QJackCtl, and the window in OBS only says “No properties available”
- Every change in the settings now closes the whole application, but this could also be due to the other differences of the edge-version and not JACK related

I hope this helps you guys out a little.

**Comment by zelyev** [comment]
I now use the OBS version that is in the Ubuntu Studio repositories. JACK works and I render with my CPU as NVENC does not work with it. Would be great if you could fix the issue with JACK in your snap version.

**Comment by flexiondotorg** [comment]
Fixed via https://github.com/snapcrafters/obs-studio/commit/d390ba384daaa6e7f3b16961982eba44dc06b999

**Comment by zelyev** [comment]
Could you please also tell us how to update snap obs-studio so the fix actually works?

sudo snap refresh
says everything is up to date

then i uninstalled it and installed it with
snap install obs-studio --edge 

But JACK, as before, does not work. Thank you.

**Comment by popey** [comment]
What revision are you running? If you run `snap info obs-studio` you'll see `installed` line which tells you. I only pushed the latest build from edge to stable about an hour ago.

**Comment by zelyev** [comment]
**It was 10 mins ago (--edge):**

name:    obs-studio
summary: OBS - Free and open source software for live streaming and screen
  recording  - Unofficial build
publisher: Snapcrafters
store-url: https://snapcraft.io/obs-studio
contact:   https://github.com/snapcrafters/obs-studio/issues
license:   unset
description: |
  This is an unofficial build of OBS Studio. Please file issues with this
  snap at https://github.com/snapcrafters/obs-studio/issues - not at the
  upstream bug tracker.
  
  OBS Studio is software designed for capturing, compositing, encoding,
  recording, and streaming video content, efficiently. We have added support
  for nvenc and VAAPI hardware accelerated GPU encoding. For Nvidia users
  choose "nvenc", for AMD and Intel users use "VAAPI"
  
  It's distributed under the GNU General Public License v2 - see the
  accompanying COPYING file for more details.
  
  To access content on external storage, manually connect to the
  removable-media plug:-
  
  `sudo snap connect obs-studio:removable-media`
  
  To access the webcam:-
  
  `sudo snap connect obs-studio:camera`
commands:
  - obs-studio
snap-id:      6uLU2MJmBURfLNz4rmL4WT2CmtVULE2u
tracking:     latest/edge
refresh-date: heute um 13:00 CEST
channels:
  latest/stable:    25.0.8 2020-05-08 (1071) 185MB -
  latest/candidate: 21.0.2 2019-04-09  (396) 151MB -
  latest/beta:      25.0.8 2020-05-08 (1071) 185MB -
  latest/edge:      25.0.8 2020-05-07 (1071) 185MB -
installed:          25.0.8            (1071) 185MB -

**It is now (--stable):**

name:    obs-studio
summary: OBS - Free and open source software for live streaming and screen
  recording  - Unofficial build
publisher: Snapcrafters
store-url: https://snapcraft.io/obs-studio
contact:   https://github.com/snapcrafters/obs-studio/issues
license:   unset
description: |
  This is an unofficial build of OBS Studio. Please file issues with this
  snap at https://github.com/snapcrafters/obs-studio/issues - not at the
  upstream bug tracker.
  
  OBS Studio is software designed for capturing, compositing, encoding,
  recording, and streaming video content, efficiently. We have added support
  for nvenc and VAAPI hardware accelerated GPU encoding. For Nvidia users
  choose "nvenc", for AMD and Intel users use "VAAPI"
  
  It's distributed under the GNU General Public License v2 - see the
  accompanying COPYING file for more details.
  
  To access content on external storage, manually connect to the
  removable-media plug:-
  
  `sudo snap connect obs-studio:removable-media`
  
  To access the webcam:-
  
  `sudo snap connect obs-studio:camera`
commands:
  - obs-studio
snap-id:      6uLU2MJmBURfLNz4rmL4WT2CmtVULE2u
tracking:     latest/stable
refresh-date: heute um 13:32 CEST
channels:
  latest/stable:    25.0.8 2020-05-08 (1071) 185MB -
  latest/candidate: 21.0.2 2019-04-09  (396) 151MB -
  latest/beta:      25.0.8 2020-05-08 (1071) 185MB -
  latest/edge:      25.0.8 2020-05-07 (1071) 185MB -
installed:          25.0.8            (1071) 185MB -


In both cases it says "No properties available" in the Jack Input source.

**Comment by popey** [comment]
if you `snap connect obs-studio:jack1` then restart obs, does it work?

**Comment by zelyev** [comment]
No.

I closed it, typed your command.

audio-playback         obs-studio:audio-playback   :audio-playback                 -
audio-record           obs-studio:audio-record     :audio-record                   -
browser-support        obs-studio:browser-support  :browser-support                -
camera                 obs-studio:camera           :camera                         -
content[gtk-3-themes]  obs-studio:gtk-3-themes     gtk-common-themes:gtk-3-themes  -
content[icon-themes]   obs-studio:icon-themes      gtk-common-themes:icon-themes   -
content[sound-themes]  obs-studio:sound-themes     gtk-common-themes:sound-themes  -
desktop                obs-studio:desktop          :desktop                        -
desktop-legacy         obs-studio:desktop-legacy   :desktop-legacy                 -
home                   obs-studio:home             :home                           -
jack1                  obs-studio:jack1            :jack1                          manual
network                obs-studio:network          :network                        -
network-bind           obs-studio:network-bind     :network-bind                   -
opengl                 obs-studio:opengl           :opengl                         -
pulseaudio             obs-studio:pulseaudio       :pulseaudio                     -
removable-media        obs-studio:removable-media  -                               -
unity7                 obs-studio:unity7           :unity7                         -
wayland                obs-studio:wayland          :wayland                        -
x11                    obs-studio:x11              :x11                            -

It connected. But the problem still persists.

**Comment by zelyev** [comment]
Is there a reason why this issue remains closed?
