### ISSUE TITLE
Please consider packaging OBS Studio with VAAPI h.264 encoding support (PR #1256)

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [snapcrafters/obs-studio#3]
Refer: [obs-ffmpeg: add linux VAAPI h.264 encoding support by GloriousEggroll · Pull Request #1256 · obsproject/obs-studio](https://github.com/obsproject/obs-studio/pull/1256)

**Comment by MGdesigner** [comment]
I support this. This is very important. Laptops with all intel CPUS today are with integrated GPUS.

**Comment by popey** [comment]
Great idea! We're in the middle of doing this for the ffmpeg snap, and once we have it strictly confined, we'll add that capability to the obs-studio snap too!

**Comment by itsrootde** [comment]
I support this too, would be really nice to see vaapi encoding

**Comment by shanefagan** [comment]
Has there been any update on this since? I didn't see any change from the ffmpeg snap or this one. Seems a bit of a missed opportunity for AMD users

**Comment by popey** [comment]
Hey Shane :). @flexiondotorg has done some work on the ffmpeg snap. While we could wholesale copy/paste the ffmpeg part from that snap into this one, and that would work, we'd considered other options. One would be to have an ffmpeg content snap. That would allow any snap to connect to it, and use the hardware accelerated ffmpeg contained in it. I'll let @flexiondotorg comment on the plan and status.

**Comment by shanefagan** [comment]
Hey popey, cool, thanks for the update. Sounds good, @flexiondotorg if you want someone to test it out I'd be happy to test it out.

**Comment by nicocarbone** [comment]
Is this implemented?
I see the option to choose ffmpeg vaapi encoder in OBS v25 installed via snap, so I figure it is. But then again this issue is still open.

**Comment by popey** [comment]
Yes, sorry, it's been there a while. Thanks!
