### ISSUE TITLE
New version 25.0.6 freezes all times

### ISSUE THREAD

**Issue by mmorena02** [snapcrafters/obs-studio#34]
Hi! I have installed the new version and when I want to use any of my two webcams, any of them wrks fine. As I wrote in the title, the software freezes after a cuple of minutes and I have to shut down my computer becouse of this.

If someone have any ideas are all welcome.

Best regards!

**Comment by flexiondotorg** [comment]
How is 25.0.8 working for you?

**Comment by mmorena02** [comment]
Hi! This new version installed from PPA is working really fine now!

**Comment by mmorena02** [comment]
> How is 25.0.8 working for you?

Hi! This new version installed from PPA is working really fine now!
