### ISSUE TITLE
OBS NDI

### ISSUE THREAD

**Issue by iced00d** [snapcrafters/obs-studio#38]
Would it be possible to add the obs-ndi.so to the .snap for the Ubuntu / Linux version?  I use my Linux box to stream from using the NDI plugin.  I know that there is an 'official' version of OBS in the PPA but it does not come with the NVENC encoder that this version does.  I'd really like to use this with NDI.  Thanks

**Comment by flexiondotorg** [comment]
Sadlt, we can't include the NDI plugin in the snap since `libndi` is not redistributable.
