### ISSUE TITLE
where do i put plugins when installing from snap?

### ISSUE THREAD

**Issue by chovy** [snapcrafters/obs-studio#46]
I have installed obs from snap, but none of the default plugin folders seem to be used.

**Comment by flecavalier** [comment]
Would really like to know too, I am trying to install the NDI plugin but I can't seem to figure out in which directory the plugin must be placed.

**Comment by flecavalier** [comment]
(If this can help, I'm on Ubuntu 18.04 using the latest version of the snap. Even though the NDI plugin is listed as being included in the snap, it doesn't actually show up in OBS)

**Comment by soonix** [comment]
In the main menu, under "File", there's an item "Show Settings Folder". I think this should lead near the right place.

**Comment by beddari** [comment]
Did anyone get NDI working?

**Comment by beddari** [comment]
So, the original question here still stands, but for NDI, installing from the edge build fixed it for me:

```
sudo snap remove obs-studio
sudo snap install obs-studio --channel=latest/edge
```

**Comment by jphein** [comment]
I also need to know this, so I can install a plugin.

**Comment by goopey7** [comment]
I found it under /snap/obs-studio/current/usr/share/obs/obs-plugins

**Comment by carnegiejunior** [comment]
~/snap/obs-studio/current/.config/obs-studio/plugins/
