### ISSUE TITLE
Cannot launch in Ubuntu 20.04 

### ISSUE THREAD

**Issue by zhamid-src** [snapcrafters/obs-studio#48]
The packaged version works fine, but this one doesn't launch.

I am on Ubuntu 20.04  and GNOME 3.36.2.

**Comment by flexiondotorg** [comment]
I can't reproduce this issue. Is this still and issue for you? Please can you share the log file (or standard output) when you attempt to start it.

**Comment by flexiondotorg** [comment]
I'll gather all segfault related feedback in issue #71. If you wish to progress this, please fopllow up there :+1:
