### ISSUE TITLE
OBS - NTFS Mounts not available

### ISSUE THREAD

**Issue by arvidurs** [snapcrafters/obs-studio#59]
Hello! 

I have a dual boot system, and have two NTFS disk which are mounted at /archive and /work both have read and write access and are working just fine in linux. 
But when I want to change the recoring path in OBS I don't have the option to cd to those disks? Any ideas? 

![image](https://user-images.githubusercontent.com/6709617/86622281-819ec900-bf74-11ea-81b6-eae4ea4730e1.png)

**Comment by flexiondotorg** [comment]
SNaps are confined and are only able to access specific paths. In order to access your NTFS volumes, mount them under `/media/archive` and `/media/work` and run `snap connect obs-studio:removable-media` :+1:
