### ISSUE TITLE
OBS Twitch Login Chat Stream Info Panels

### ISSUE THREAD

**Issue by arvidurs** [snapcrafters/obs-studio#60]
Hello! Last issue - 

When I run OBS from Windows I get a twitch login screen, instead of providing stream keys. ( I think that's a newer version). 
The great thing with that is, after logging in, I Chat and Stream options pop up, that way I can update the info before starting the stream. 

Is that something you can look in to? 
![image](https://user-images.githubusercontent.com/6709617/86622520-d7737100-bf74-11ea-9ad1-2ec19abb6cf4.png)

Arvid

**Comment by flexiondotorg** [comment]
What you describe is not currently a feature of upstream OBS Studio on Linux.

**Comment by moscoquera** [comment]
> 

well that feature is currently available in the upstream OBS version but not in the snap one

**Comment by koo5** [comment]
note: this isn't a dealbreaker, the docks just load pages like https://dashboard.twitch.tv/popout/u/<username>/stream-manager/edit-stream-info
