### ISSUE TITLE
Window capture is not refreshing on output

### ISSUE THREAD

**Issue by hskurumin** [snapcrafters/obs-studio#63]
Hi, folks!
     I was using OBS-studio with Ubuntu Studio 20.04 - it was awesome. However, this week I changed the hard drive and had to install the operational system from scratch. I installed the same version of the OS: Ubuntu Studio 20.04. I installed OBS Studio 25.0.8-modified (new version). So... It starts and works normaly, but when I record from a "Window Capture" the image of the output does not refresh (audio is ok and the cursor moves, but when I change slides, it won't update - neither on OBS nor on the output). On the other hand, if I record from "Screen Capture" (which does not fit my needs), it works 100% normaly: both OBS and output video refresh the slides as I change them. Is that a build issue or is there something wrong with my OS?

When I use `snap run obs-studio` and record from window capture, I get this:

```
Qt: Session management error: Authentication Rejected, reason : None of the authentication
protocols specified are supported and host-based authentication failed
Attempted path: share/obs/obs-studio/locale/en-US.ini
Attempted path: /usr/share/obs/obs-studio/locale/en-US.ini
Attempted path: share/obs/obs-studio/themes/Dark.qss
Attempted path: /usr/share/obs/obs-studio/themes/Dark.qss
info: CPU Name: Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz
info: CPU Speed: 1719.517MHz
info: Physical Cores: 2, Logical Cores: 4
info: Physical Memory: 7877MB Total, 5607MB Free
info: Kernel Version: Linux 5.4.0-42-lowlatency
info: Distribution: "Ubuntu Core" "18"
info: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.20.8
info: Portable mode: false
Attempted path: share/obs/obs-studio/themes/Dark/no_sources.svg
Attempted path: /usr/share/obs/obs-studio/themes/Dark/no_sources.svg
QMetaObject::connectSlotsByName: No matching signal for on_advAudioProps_clicked()
QMetaObject::connectSlotsByName: No matching signal for on_advAudioProps_destroyed()
QMetaObject::connectSlotsByName: No matching signal for on_actionGridMode_triggered()
QMetaObject::connectSlotsByName: No matching signal for on_program_customContextMenuRequested(QPoint)
info: OBS 25.0.8-modified (linux)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
	samples per sec: 44100
	speakers:        2
info: ---------------------------------
info: Initializing OpenGL...
info: Loading up OpenGL on adapter VMware, Inc. llvmpipe (LLVM 9.0, 256 bits)
info: OpenGL loaded successfully, version 3.3 (Core Profile) Mesa 19.2.8, shading language 3.30
info: ---------------------------------
info: video settings reset:
	base resolution:   1366x768
	output resolution: 680x384
	downscale filter:  Bicubic
	fps:               30/1
	format:            NV12
	YUV mode:          601/Partial
info: NV12 texture support not available
info: Audio monitoring device:
	name: Default
	id: default
info: ---------------------------------
info: [StreamFX] Loading Version 0.8.0.10-95f022fe
Unknown property box-shadow
Unknown property cursor
libpng warning: iCCP: known incorrect sRGB profile
info: [StreamFX] Loaded Version 0.8.0.10-95f022fe
warning: Failed to load 'en-US' text for module: 'decklink-ouput-ui.so'
libUIOHook: Cross-platfrom userland keyboard and mouse hooking.
Copyright (C) 2006-2015 Alexander Barker.  All Rights Received.
https://github.com/kwhat/libuiohook/

libUIOHook is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

libUIOHook is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

libDeckLinkAPI.so: cannot open shared object file: No such file or directory
warning: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
info: No blackmagic support
info: [obs-browser]: Version 2.8.6
error: os_dlopen(libnvidia-encode.so.1->libnvidia-encode.so.1): libnvidia-encode.so.1: cannot open shared object file: No such file or directory

info: FFMPEG VAAPI supported
info: [obs-ndi] hello ! (version 4.9.1)
info: [obs-ndi] Trying ''
info: [obs-ndi] Trying '/usr/lib'
info: [obs-ndi] Trying '/usr/local/lib'
info: [obs-ndi] Found NDI library at '/usr/local/lib/libndi.so.4'
info: [obs-ndi] NDI runtime loaded successfully
info: [obs-ndi] NDI library initialized successfully (NDI SDK LINUX 22:02:16 May 19 2020 4.5.2)
info: [obs-websocket] you can haz websockets (version 4.7.0)
info: [obs-websocket] qt version (compile-time): 5.9.5 ; qt version (run-time): 5.9.5
info: [obs-websocket] module loaded!
warning: Failed to load 'en-US' text for module: 'replay-source.so'
info: VLC found, VLC video source enabled
info: ---------------------------------
info:   Loaded Modules:
info:     vlc-video.so
info:     text-freetype2.so
info:     spectralizer.so
info:     source-switcher.so
info:     scrab.so
info:     rtmp-services.so
info:     replay-source.so
info:     obs-x264.so
info:     obs-websocket.so
info:     obs-vintage-filter.so
info:     obs-transitions.so
info:     obs-transition-matrix.so
info:     obs-outputs.so
info:     obs-ndi.so
info:     obs-libfdk.so
info:     obs-filters.so
info:     obs-ffmpeg.so
info:     obs-browser.so
info:     move-transition.so
info:     linux-v4l2.so
info:     linux-pulseaudio.so
info:     linux-jack.so
info:     linux-decklink.so
info:     linux-capture.so
info:     linux-alsa.so
info:     input-overlay.so
info:     image-source.so
info:     frontend-tools.so
info:     freeze-filter.so
info:     decklink-ouput-ui.so
info:     advanced-scene-switcher.so
info:     StreamFX.so
info: ---------------------------------
error: os_dlopen(../obs-plugins/obs-browser->../obs-plugins/obs-browser.so): ../obs-plugins/obs-browser.so: cannot open shared object file: No such file or directory

info: ==== Startup complete ===============================================
error: Service '' not found
info: All scene data cleared
info: ------------------------------------------------
info: pulse-input: Server name: 'pulseaudio 13.99.1'
info: pulse-input: Audio format: s16le, 44100 Hz, 2 channels
info: pulse-input: Started recording from 'alsa_output.pci-0000_00_1b.0.analog-stereo.monitor'
info: [Loaded global audio device]: 'Desktop Audio'
info: pulse-input: Server name: 'pulseaudio 13.99.1'
info: pulse-input: Audio format: s16le, 44100 Hz, 2 channels
info: pulse-input: Started recording from 'alsa_input.pci-0000_00_1b.0.analog-stereo'
info: [Loaded global audio device]: 'Mic/Aux'
info: xshm-input: Geometry 1366x768 @ 0,0
info: Switched to scene 'Scene'
info: ------------------------------------------------
info: Loaded scenes:
info: - scene 'Scene':
info:     - source: 'Screen Capture (XSHM)' (xshm_input)
info:     - source: 'Window Capture (Xcomposite)' (xcomposite_input)
info: ------------------------------------------------
info: [obs-websocket] server started successfully on port 4444
info: [obs-websocket] io thread started
Unknown property box-shadow
Unknown property cursor
Attempted path: share/obs/obs-studio/images/overflow.png
Attempted path: /usr/share/obs/obs-studio/images/overflow.png
info: adding 46 milliseconds of audio buffering, total audio buffering is now 46 milliseconds (source: Mic/Aux)

info: xcompcap: [window-capture: 'Window Capture (Xcomposite)'] update settings:
	title: xfce4-panel
	class: xfce4-panel
	Bit depth: 32
	Found proper GLXFBConfig (in 110): yes

info: xcompcap: [window-capture: 'Window Capture (Xcomposite)'] update settings:
	title: xfce4-panel
	class: xfce4-panel
	Bit depth: 32
	Found proper GLXFBConfig (in 110): yes

info: xcompcap: [window-capture: 'Window Capture (Xcomposite)'] update settings:
	title: P.pdf  Apresenta��o do PowerPoint
	class: atril
	Bit depth: 24
	Found proper GLXFBConfig (in 110): yes

info: ---------------------------------
info: [x264 encoder: 'simple_h264_recording'] preset: veryfast
info: [x264 encoder: 'simple_h264_recording'] profile: high
info: [x264 encoder: 'simple_h264_recording'] settings:
	rate_control: CRF
	bitrate:      0
	buffer size:  0
	crf:          17
	fps_num:      30
	fps_den:      1
	width:        680
	height:       384
	keyint:       250

info: libfdk_aac encoder created
info: libfdk_aac bitrate: 192, channels: 2
info: ==== Recording Start ===============================================
info: [ffmpeg muxer: 'simple_file_output'] Writing file '/home/marcelo/Vídeos/2020-07-29 12-20-35.mkv'...
[matroska @ 0x55a0e3b37f80] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[matroska @ 0x55a0e3b37f80] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
info: [ffmpeg muxer: 'simple_file_output'] Output of file '/home/marcelo/Vídeos/2020-07-29 12-20-35.mkv' stopped
info: Output 'simple_file_output': stopping
info: Output 'simple_file_output': Total frames output: 135
info: Output 'simple_file_output': Total drawn frames: 143 (156 attempted)
info: Output 'simple_file_output': Number of lagged frames due to rendering lag/stalls: 13 (8.3%)
info: ==== Recording Stop ================================================
info: libfdk_aac encoder destroyed
info: xcompcap: [window-capture: 'Window Capture (Xcomposite)'] update settings:
	title: P.pdf  Apresenta��o do PowerPoint
	class: atril
	Bit depth: 24
	Found proper GLXFBConfig (in 110): yes
```

**Comment by hskurumin** [comment]
> Please refresh obs-studio from the stable channel and let me know if this is still an issue you are still experiencing.

Hi Martin! Thanks for replying! I uninstalled it as you said and reinstalled the version 25.0.8 form the latest/stable channel. The software does not even open anymore. When I use `snap run obs-studio` I get this:

Qt: Session management error: Authentication Rejected, reason : None of the authentication protocols specified are supported and host-based authentication failed
Attempted path: share/obs/obs-studio/locale/en-US.ini
Attempted path: /usr/share/obs/obs-studio/locale/en-US.ini
Attempted path: share/obs/obs-studio/themes/Dark.qss
Attempted path: /usr/share/obs/obs-studio/themes/Dark.qss
info: CPU Name: Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz
info: CPU Speed: 1702.252MHz
info: Physical Cores: 2, Logical Cores: 4
info: Physical Memory: 7877MB Total, 3326MB Free
info: Kernel Version: Linux 5.4.0-42-lowlatency
info: Distribution: "Ubuntu Core" "18"
info: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.20.8
info: Portable mode: false
Attempted path: share/obs/obs-studio/themes/Dark/no_sources.svg
Attempted path: /usr/share/obs/obs-studio/themes/Dark/no_sources.svg
QMetaObject::connectSlotsByName: No matching signal for on_advAudioProps_clicked()
QMetaObject::connectSlotsByName: No matching signal for on_advAudioProps_destroyed()
QMetaObject::connectSlotsByName: No matching signal for on_actionGridMode_triggered()
QMetaObject::connectSlotsByName: No matching signal for on_program_customContextMenuRequested(QPoint)
info: OBS 25.0.8-modified (linux)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
	samples per sec: 44100
	speakers:        2
info: ---------------------------------
info: Initializing OpenGL...
info: Loading up OpenGL on adapter VMware, Inc. llvmpipe (LLVM 10.0.0, 256 bits)
info: OpenGL loaded successfully, version 3.3 (Core Profile) Mesa 20.0.8, shading language 3.30
info: ---------------------------------
info: video settings reset:
	base resolution:   1366x768
	output resolution: 1092x614
	downscale filter:  Bicubic
	fps:               30/1
	format:            NV12
	YUV mode:          601/Partial
info: NV12 texture support not available
info: Audio monitoring device:
	name: Default
	id: default
info: ---------------------------------
info: [StreamFX] Loading Version 0.8.3.0-ee225959
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
info: [StreamFX] Loaded Version 0.8.3.0-ee225959
warning: Failed to load 'en-US' text for module: 'decklink-ouput-ui.so'
libUIOHook: Cross-platfrom userland keyboard and mouse hooking.
Copyright (C) 2006-2015 Alexander Barker.  All Rights Received.
https://github.com/kwhat/libuiohook/

libUIOHook is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

libUIOHook is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

info: [pango]: Loaded system fontconfig
libDeckLinkAPI.so: cannot open shared object file: No such file or directory
warning: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
info: No blackmagic support
info: [obs-browser]: Version 2.8.6
error: os_dlopen(libnvidia-encode.so.1->libnvidia-encode.so.1): libnvidia-encode.so.1: cannot open shared object file: No such file or directory

info: FFMPEG VAAPI supported
info: [obs-ndi] hello ! (version 4.9.1)
info: [obs-ndi] Trying ''
info: [obs-ndi] Trying '/usr/lib'
info: [obs-ndi] Trying '/usr/local/lib'
info: [obs-ndi] Found NDI library at '/usr/local/lib/libndi.so.4'
info: [obs-ndi] NDI runtime loaded successfully
info: [obs-ndi] NDI library initialized successfully (NDI SDK LINUX 18:32:11 Jun 30 2020 4.5.3)
warning: Failed to load 'en-US' text for module: 'obs-vnc.so'
info: [obs-vnc] plugin loaded successfully (version 0.1.0)
info: [obs-websocket] you can haz websockets (version 4.8.0)
info: [obs-websocket] qt version (compile-time): 5.9.5 ; qt version (run-time): 5.9.5
info: [obs-websocket] module loaded!
warning: Failed to load 'en-US' text for module: 'replay-source.so'
info: VLC found, VLC video source enabled
info: ---------------------------------
info:   Loaded Modules:
info:     vlc-video.so
info:     v4l2sink.so
info:     text-freetype2.so
info:     spectralizer.so
info:     source-switcher.so
info:     scrab.so
info:     rtmp-services.so
info:     replay-source.so
info:     obs-x264.so
info:     obs-websocket.so
info:     obs-vnc.so
info:     obs-vintage-filter.so
info:     obs-transitions.so
info:     obs-transition-matrix.so
info:     obs-rgb-levels-filter.so
info:     obs-outputs.so
info:     obs-ndi.so
info:     obs-libfdk.so
info:     obs-filters.so
info:     obs-ffmpeg.so
info:     obs-browser.so
info:     move-transition.so
info:     linux-v4l2.so
info:     linux-pulseaudio.so
info:     linux-jack.so
info:     linux-decklink.so
info:     linux-capture.so
info:     linux-alsa.so
info:     libtext-pango.so
info:     input-overlay.so
info:     image-source.so
info:     frontend-tools.so
info:     freeze-filter.so
info:     dynamic-delay.so
info:     dir-watch-media.so
info:     decklink-ouput-ui.so
info:     advanced-scene-switcher.so
info:     StreamFX.so
info: ---------------------------------
error: os_dlopen(../obs-plugins/obs-browser->../obs-plugins/obs-browser.so): ../obs-plugins/obs-browser.so: cannot open shared object file: No such file or directory

info: ==== Startup complete ===============================================
error: Service '' not found
info: No scene file found, creating default scene
info: All scene data cleared
info: ------------------------------------------------
info: pulse-input: Server name: 'pulseaudio 13.99.1'
info: pulse-input: Audio format: s16le, 44100 Hz, 2 channels
info: pulse-input: Started recording from 'alsa_output.pci-0000_00_1b.0.analog-stereo.monitor'
info: pulse-input: Server name: 'pulseaudio 13.99.1'
info: pulse-input: Audio format: s16le, 44100 Hz, 2 channels
info: pulse-input: Started recording from 'alsa_input.pci-0000_00_1b.0.analog-stereo'
info: Switched to scene 'Scene'
warning: Failed to glob scene collections
Falha de segmentação (imagem do núcleo gravada)

**Comment by flexiondotorg** [comment]
Please re-test. The revision of OBS Studio in the stable has the intermitent crashes fixed :+1: Also, can you confirm that you're running in a VM?

**Comment by flexiondotorg** [comment]
Closed due to inactivity.
