### ISSUE TITLE
Segfaults on start-up

### ISSUE THREAD

**Issue by MasoodAhmad** [snapcrafters/obs-studio#71]
$ sudo snap install obs-studio
obs-studio 25.0.8 from Snapcrafters installed
user1@user1-M6700:~$ obs-studio 
Qt: Session management error: Authentication Rejected, reason : None of the authentication protocols specified are supported and host-based authentication failed
Attempted path: share/obs/obs-studio/locale/en-US.ini
Attempted path: /usr/share/obs/obs-studio/locale/en-US.ini
Attempted path: share/obs/obs-studio/themes/Dark.qss
Attempted path: /usr/share/obs/obs-studio/themes/Dark.qss
info: CPU Name: Intel(R) Core(TM) i7-3740QM CPU @ 2.70GHz
info: CPU Speed: 3024.319MHz
info: Physical Cores: 4, Logical Cores: 8
info: Physical Memory: 23939MB Total, 1472MB Free
info: Kernel Version: Linux 5.4.0-42-generic
info: Distribution: "Ubuntu Core" "18"
info: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.20.8
info: Portable mode: false
Attempted path: share/obs/obs-studio/themes/Dark/no_sources.svg
Attempted path: /usr/share/obs/obs-studio/themes/Dark/no_sources.svg
QMetaObject::connectSlotsByName: No matching signal for on_advAudioProps_clicked()
QMetaObject::connectSlotsByName: No matching signal for on_advAudioProps_destroyed()
QMetaObject::connectSlotsByName: No matching signal for on_actionGridMode_triggered()
QMetaObject::connectSlotsByName: No matching signal for on_program_customContextMenuRequested(QPoint)
info: OBS 25.0.8-modified (linux)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
        samples per sec: 44100
        speakers:        2
info: ---------------------------------
info: Initializing OpenGL...
info: Loading up OpenGL on adapter NVIDIA Corporation Quadro K3000M/PCIe/SSE2
info: OpenGL loaded successfully, version 3.3.0 NVIDIA 390.138, shading language 3.30 NVIDIA via Cg compiler
info: ---------------------------------
info: video settings reset:
        base resolution:   1440x900
        output resolution: 1152x720
        downscale filter:  Bicubic
        fps:               30/1
        format:            NV12
        YUV mode:          601/Partial
info: NV12 texture support not available
info: Audio monitoring device:
        name: Default
        id: default
info: ---------------------------------
info: [StreamFX] Loading Version 0.8.3.0-ee225959
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
info: [StreamFX] Loaded Version 0.8.3.0-ee225959
warning: Failed to load 'en-US' text for module: 'decklink-ouput-ui.so'
libUIOHook: Cross-platfrom userland keyboard and mouse hooking.
Copyright (C) 2006-2015 Alexander Barker.  All Rights Received.
https://github.com/kwhat/libuiohook/

libUIOHook is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

libUIOHook is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

info: [pango]: Loaded system fontconfig
libDeckLinkAPI.so: cannot open shared object file: No such file or directory
warning: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
info: No blackmagic support
info: [obs-browser]: Version 2.8.6
info: NVENC supported
info: FFMPEG VAAPI supported
info: [obs-ndi] hello ! (version 4.9.1)
info: [obs-ndi] Trying ''
info: [obs-ndi] Trying '/usr/lib'
info: [obs-ndi] Trying '/usr/local/lib'
info: [obs-ndi] Found NDI library at '/usr/local/lib/libndi.so.4'
info: [obs-ndi] NDI runtime loaded successfully
info: [obs-ndi] NDI library initialized successfully (NDI SDK LINUX 18:32:11 Jun 30 2020 4.5.3)
warning: Failed to load 'en-US' text for module: 'obs-vnc.so'
info: [obs-vnc] plugin loaded successfully (version 0.1.0)
info: [obs-websocket] you can haz websockets (version 4.8.0)
info: [obs-websocket] qt version (compile-time): 5.9.5 ; qt version (run-time): 5.9.5
info: [obs-websocket] module loaded!
warning: Failed to load 'en-US' text for module: 'replay-source.so'
info: VLC found, VLC video source enabled
info: ---------------------------------
info:   Loaded Modules:
info:     vlc-video.so
info:     v4l2sink.so
info:     text-freetype2.so
info:     spectralizer.so
info:     source-switcher.so
info:     scrab.so
info:     rtmp-services.so
info:     replay-source.so
info:     obs-x264.so
info:     obs-websocket.so
info:     obs-vnc.so
info:     obs-vintage-filter.so
info:     obs-transitions.so
info:     obs-transition-matrix.so
info:     obs-rgb-levels-filter.so
info:     obs-outputs.so
info:     obs-ndi.so
info:     obs-libfdk.so
info:     obs-filters.so
info:     obs-ffmpeg.so
info:     obs-browser.so
info:     move-transition.so
info:     linux-v4l2.so
info:     linux-pulseaudio.so
info:     linux-jack.so
info:     linux-decklink.so
info:     linux-capture.so
info:     linux-alsa.so
info:     libtext-pango.so
info:     input-overlay.so
info:     image-source.so
info:     frontend-tools.so
info:     freeze-filter.so
info:     dynamic-delay.so
info:     dir-watch-media.so
info:     decklink-ouput-ui.so
info:     advanced-scene-switcher.so
info:     StreamFX.so
info: ---------------------------------
error: os_dlopen(../obs-plugins/obs-browser->../obs-plugins/obs-browser.so): ../obs-plugins/obs-browser.so: cannot open shared object file: No such file or directory

info: ==== Startup complete ===============================================
error: Service '' not found
info: No scene file found, creating default scene
info: All scene data cleared
info: ------------------------------------------------
info: pulse-input: Server name: 'pulseaudio 13.99.1'
info: pulse-input: Audio format: s16le, 44100 Hz, 2 channels
info: pulse-input: Started recording from 'alsa_output.pci-0000_00_1b.0.analog-stereo.monitor'
info: pulse-input: Server name: 'pulseaudio 13.99.1'
info: pulse-input: Audio format: s16le, 48000 Hz, 2 channels
info: pulse-input: Started recording from 'alsa_input.usb-046d_Logitech_Webcam_C930e_26E65FCF-02.analog-stereo'
info: Switched to scene 'Scene'
warning: Failed to glob scene collections
Segmentation fault (core dumped)

**Comment by flexiondotorg** [comment]
I can't reproduce this issue.

**Comment by flexiondotorg** [comment]
It looks like your Quadro K3000M support the 418 NVIDIA drivers. Please test using the upgrade 418 drivers.

**Comment by sastrugi56** [comment]
I'm having the same issue. I tried turning off Wayland but it didn't help.  I've also updated my system.

$ obs-studio
Qt: Session management error: None of the authentication protocols specified are supported
Attempted path: share/obs/obs-studio/locale/en-US.ini
Attempted path: /usr/share/obs/obs-studio/locale/en-US.ini
Attempted path: share/obs/obs-studio/themes/Dark.qss
Attempted path: /usr/share/obs/obs-studio/themes/Dark.qss
info: CPU Name: Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz
info: CPU Speed: 1817.188MHz
info: CPU Name: Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz
info: CPU Speed: 2026.061MHz
info: CPU Name: Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz
info: CPU Speed: 1693.174MHz
info: CPU Name: Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz
info: CPU Speed: 2182.705MHz
info: Physical Cores: 12, Logical Cores: 24
info: Physical Memory: 24084MB Total, 16967MB Free
info: Kernel Version: Linux 5.4.0-42-generic
info: Distribution: "Ubuntu Core" "18"
info: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.20.8
info: Portable mode: false
Attempted path: share/obs/obs-studio/themes/Dark/no_sources.svg
Attempted path: /usr/share/obs/obs-studio/themes/Dark/no_sources.svg
QMetaObject::connectSlotsByName: No matching signal for on_advAudioProps_clicked()
QMetaObject::connectSlotsByName: No matching signal for on_advAudioProps_destroyed()
QMetaObject::connectSlotsByName: No matching signal for on_actionGridMode_triggered()
QMetaObject::connectSlotsByName: No matching signal for on_program_customContextMenuRequested(QPoint)
info: OBS 25.0.8-modified (linux)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
	samples per sec: 44100
	speakers:        2
info: ---------------------------------
info: Initializing OpenGL...
info: Loading up OpenGL on adapter NVIDIA Corporation Quadro FX 1800/PCIe/SSE2
info: OpenGL loaded successfully, version 3.3.0 NVIDIA 340.108, shading language 3.30 NVIDIA via Cg compiler
info: ---------------------------------
info: video settings reset:
	base resolution:   1920x1080
	output resolution: 1280x720
	downscale filter:  Bicubic
	fps:               30/1
	format:            NV12
	YUV mode:          601/Partial
info: NV12 texture support not available
info: Audio monitoring device:
	name: Default
	id: default
info: ---------------------------------
info: [StreamFX] Loading Version 0.8.3.0-ee225959
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
info: [StreamFX] Loaded Version 0.8.3.0-ee225959
warning: Failed to load 'en-US' text for module: 'decklink-ouput-ui.so'
libUIOHook: Cross-platfrom userland keyboard and mouse hooking.
Copyright (C) 2006-2015 Alexander Barker.  All Rights Received.
https://github.com/kwhat/libuiohook/

libUIOHook is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

libUIOHook is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

info: [pango]: Loaded system fontconfig
libDeckLinkAPI.so: cannot open shared object file: No such file or directory
warning: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
info: No blackmagic support
info: [obs-browser]: Version 2.8.6
info: NVENC supported
info: FFMPEG VAAPI supported
info: [obs-ndi] hello ! (version 4.9.1)
info: [obs-ndi] Trying ''
info: [obs-ndi] Trying '/usr/lib'
info: [obs-ndi] Trying '/usr/local/lib'
info: [obs-ndi] Found NDI library at '/usr/local/lib/libndi.so.4'
info: [obs-ndi] NDI runtime loaded successfully
info: [obs-ndi] NDI library initialized successfully (NDI SDK LINUX 18:32:11 Jun 30 2020 4.5.3)
warning: Failed to load 'en-US' text for module: 'obs-vnc.so'
info: [obs-vnc] plugin loaded successfully (version 0.1.0)
info: [obs-websocket] you can haz websockets (version 4.8.0)
info: [obs-websocket] qt version (compile-time): 5.9.5 ; qt version (run-time): 5.9.5
info: [obs-websocket] module loaded!
warning: Failed to load 'en-US' text for module: 'replay-source.so'
info: VLC found, VLC video source enabled
info: ---------------------------------
info:   Loaded Modules:
info:     vlc-video.so
info:     v4l2sink.so
info:     text-freetype2.so
info:     spectralizer.so
info:     source-switcher.so
info:     scrab.so
info:     rtmp-services.so
info:     replay-source.so
info:     obs-x264.so
info:     obs-websocket.so
info:     obs-vnc.so
info:     obs-vintage-filter.so
info:     obs-transitions.so
info:     obs-transition-matrix.so
info:     obs-rgb-levels-filter.so
info:     obs-outputs.so
info:     obs-ndi.so
info:     obs-libfdk.so
info:     obs-filters.so
info:     obs-ffmpeg.so
info:     obs-browser.so
info:     move-transition.so
info:     linux-v4l2.so
info:     linux-pulseaudio.so
info:     linux-jack.so
info:     linux-decklink.so
info:     linux-capture.so
info:     linux-alsa.so
info:     libtext-pango.so
info:     input-overlay.so
info:     image-source.so
info:     frontend-tools.so
info:     freeze-filter.so
info:     dynamic-delay.so
info:     dir-watch-media.so
info:     decklink-ouput-ui.so
info:     advanced-scene-switcher.so
info:     StreamFX.so
info: ---------------------------------
error: os_dlopen(../obs-plugins/obs-browser->../obs-plugins/obs-browser.so): ../obs-plugins/obs-browser.so: cannot open shared object file: No such file or directory

info: ==== Startup complete ===============================================
error: Service '' not found
info: No scene file found, creating default scene
info: All scene data cleared
info: ------------------------------------------------
info: pulse-input: Server name: 'pulseaudio 13.99.1'
info: pulse-input: Audio format: s16le, 44100 Hz, 2 channels
info: pulse-input: Started recording from 'alsa_output.pci-0000_00_1b.0.analog-stereo.monitor'
info: Switched to scene 'Scene'
warning: Failed to glob scene collections
Segmentation fault (core dumped)

**Comment by canalocaradoti** [comment]
I have the same problem and I can't run obs-studio via snap. I tried to report on [my topic](https://github.com/snapcrafters/obs-studio/issues/61) that I was reporting excessive CPU usage, but it was closed without explaining why the CPU was overused.

[SNAPOBSStudio2..txt](https://github.com/snapcrafters/obs-studio/files/5134571/SNAPOBSStudio2.txt) my departure from the terminal.

**Comment by flexiondotorg** [comment]
Please run `snap connections obs-studio` from a terminal and paste the output here and also include startup logs.

**Comment by rpodcast** [comment]
I am having similar segfaults (see my comment on #68) but here's my output of `snap connections obs-studio`:

```
eric@system76-pc:~$ snap connections obs-studio
Interface              Plug                        Slot                            Notes
audio-playback         obs-studio:audio-playback   :audio-playback                 -
audio-record           obs-studio:audio-record     :audio-record                   -
avahi-control          obs-studio:avahi-control    :avahi-control                  manual
browser-support        obs-studio:browser-support  :browser-support                -
camera                 obs-studio:camera           :camera                         -
content[gtk-3-themes]  obs-studio:gtk-3-themes     gtk-common-themes:gtk-3-themes  -
content[icon-themes]   obs-studio:icon-themes      gtk-common-themes:icon-themes   -
content[sound-themes]  obs-studio:sound-themes     gtk-common-themes:sound-themes  -
desktop                obs-studio:desktop          :desktop                        -
desktop-legacy         obs-studio:desktop-legacy   :desktop-legacy                 -
home                   obs-studio:home             :home                           -
jack1                  obs-studio:jack1            :jack1                          manual
joystick               obs-studio:joystick         :joystick                       manual
network                obs-studio:network          :network                        -
network-bind           obs-studio:network-bind     :network-bind                   -
opengl                 obs-studio:opengl           :opengl                         -
pulseaudio             obs-studio:pulseaudio       :pulseaudio                     -
removable-media        obs-studio:removable-media  :removable-media                manual
unity7                 obs-studio:unity7           :unity7                         -
wayland                obs-studio:wayland          :wayland                        -
x11                    obs-studio:x11              :x11                            -
```

**Comment by flexiondotorg** [comment]
I have reproduced a segfault here by starting the snap with no pre-existing user data in `~/snap/obs-studio`.

**Comment by flexiondotorg** [comment]
Initial investigations suggest Scene Switcher 1.6.2 might be to blame.
