### ISSUE TITLE
100% CPU while idle

### ISSUE THREAD

**Issue by kaya3** [snapcrafters/obs-studio#72]
In revision 1117 and the current revision 1118, OBS uses 100% of one of my CPU cores while idle; this coincides with an "about StreamFX" dialog popping up on first use of that version of OBS, and there is [an unfixed issue on the StreamFX issue tracker](https://github.com/Xaymar/obs-StreamFX/issues/68) which is perhaps related.

I had previously solved this about a month ago by reverting to an earlier revision without StreamFX, but it seems snap automatically updated OBS today and also removed the old (working) revision from my hard disk without asking me. I think the old revision was somewhere around 1070; if possible, please make available the most recent revision before StreamFX was added so I can install that one again.

**Comment by flexiondotorg** [comment]
Please can you share log files from OBS and also `htop` or similar for your systems while OBS Studio is running.

**Comment by flexiondotorg** [comment]
Please can you also run `snap connections obs-studio` from a terminal and paste the output here.

**Comment by flexiondotorg** [comment]
Rebuilding the OBS Studio snap, enabling one 3rd party plugin at a time, to figure out what is causing this...

**Comment by flexiondotorg** [comment]
The Input Overlay plugin is the cause of high CPU load.
