### ISSUE TITLE
obs doesnt work on Centos

### ISSUE THREAD

**Issue by eduardocf22** [snapcrafters/obs-studio#73]
I can not opens obs-studio on Centos 8
I already installed but obs-studio don't start
I tired to use the icon applications OBS on Centos 8 but the situation is similar
Please your comments and advice
Thanks

**Comment by eduardocf22** [comment]
Attached bellow the errors:

Aug 23 23:43:42 localhost obs-studio_obs-studio.desktop[12529]: QSocketNotifier: Can only be used with threads started with QThread
Aug 23 23:43:42 localhost obs-studio_obs-studio.desktop[12529]: Using Wayland-EGL
Aug 23 23:43:42 localhost obs-studio_obs-studio.desktop[12529]: /usr/share/libdrm/amdgpu.ids: No such file or directory
Aug 23 23:43:42 localhost obs-studio_obs-studio.desktop[12529]: Attempted path: share/obs/obs-studio/locale/en-US.ini
Aug 23 23:43:42 localhost obs-studio_obs-studio.desktop[12529]: Attempted path: /usr/share/obs/obs-studio/locale/en-US.ini
Aug 23 23:43:42 localhost obs-studio_obs-studio.desktop[12529]: Attempted path: share/obs/obs-studio/themes/Dark.qss
Aug 23 23:43:42 localhost obs-studio_obs-studio.desktop[12529]: Attempted path: /usr/share/obs/obs-studio/themes/Dark.qss
Aug 23 23:43:42 localhost obs-studio_obs-studio.desktop[12529]: info: CPU Name: AMD Ryzen 3 3200U with Radeon Vega Mobile Gfx
Aug 23 23:43:42 localhost obs-studio_obs-studio.desktop[12529]: info: CPU Speed: 2590.323MHz
Aug 23 23:43:42 localhost obs-studio_obs-studio.desktop[12529]: info: Physical Cores: 2, Logical Cores: 4
Aug 23 23:43:42 localhost obs-studio_obs-studio.desktop[12529]: info: Physical Memory: 5667MB Total, 884MB Free
Aug 23 23:43:42 localhost obs-studio_obs-studio.desktop[12529]: info: Kernel Version: Linux 4.18.0-193.14.2.el8_2.x86_64
Aug 23 23:43:42 localhost obs-studio_obs-studio.desktop[12529]: info: Distribution: "Ubuntu Core" "18"
Aug 23 23:43:42 localhost obs-studio_obs-studio.desktop[12529]: info: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.20.6
Aug 23 23:43:42 localhost obs-studio_obs-studio.desktop[12529]: info: Portable mode: false
Aug 23 23:43:42 localhost obs-studio_obs-studio.desktop[12529]: QMetaObject::connectSlotsByName: No matching signal for on_advAudioProps_clicked()
Aug 23 23:43:42 localhost obs-studio_obs-studio.desktop[12529]: QMetaObject::connectSlotsByName: No matching signal for on_advAudioProps_destroyed()
Aug 23 23:43:42 localhost obs-studio_obs-studio.desktop[12529]: QMetaObject::connectSlotsByName: No matching signal for on_actionGridMode_triggered()
Aug 23 23:43:42 localhost obs-studio_obs-studio.desktop[12529]: QMetaObject::connectSlotsByName: No matching signal for on_program_customContextMenuRequested(QPoint)
Aug 23 23:43:42 localhost obs-studio_obs-studio.desktop[12529]: Attempted path: share/obs/obs-studio/themes/Dark/no_sources.svg
Aug 23 23:43:42 localhost obs-studio_obs-studio.desktop[12529]: Attempted path: /usr/share/obs/obs-studio/themes/Dark/no_sources.svg
Aug 23 23:43:42 localhost obs-studio_obs-studio.desktop[12529]: info: OBS 25.0.8-modified (linux)
Aug 23 23:43:42 localhost obs-studio_obs-studio.desktop[12529]: info: ---------------------------------
Aug 23 23:43:42 localhost obs-studio_obs-studio.desktop[12529]: info: ---------------------------------
Aug 23 23:43:42 localhost obs-studio_obs-studio.desktop[12529]: info: audio settings reset:
Aug 23 23:43:42 localhost obs-studio_obs-studio.desktop[12529]: #011samples per sec: 44100
Aug 23 23:43:42 localhost obs-studio_obs-studio.desktop[12529]: #011speakers:        2
Aug 23 23:43:42 localhost obs-studio_obs-studio.desktop[12529]: info: ---------------------------------
Aug 23 23:43:42 localhost obs-studio_obs-studio.desktop[12529]: info: Initializing OpenGL...
Aug 23 23:43:42 localhost obs-studio_obs-studio.desktop[12529]: info: Loading up OpenGL on adapter X.Org AMD RAVEN2 (DRM 3.33.0, 4.18.0-193.14.2.el8_2.x86_64, LLVM 10.0.0)
Aug 23 23:43:42 localhost obs-studio_obs-studio.desktop[12529]: info: OpenGL loaded successfully, version 4.6 (Core Profile) Mesa 20.0.8, shading language 4.60
Aug 23 23:43:42 localhost obs-studio_obs-studio.desktop[12529]: info: ---------------------------------
Aug 23 23:43:42 localhost obs-studio_obs-studio.desktop[12529]: info: video settings reset:
Aug 23 23:43:42 localhost obs-studio_obs-studio.desktop[12529]: #011base resolution:   1366x768
Aug 23 23:43:42 localhost obs-studio_obs-studio.desktop[12529]: #011output resolution: 1092x614
Aug 23 23:43:42 localhost obs-studio_obs-studio.desktop[12529]: #011downscale filter:  Bicubic
Aug 23 23:43:42 localhost obs-studio_obs-studio.desktop[12529]: #011fps:               30/1
Aug 23 23:43:42 localhost obs-studio_obs-studio.desktop[12529]: #011format:            NV12
Aug 23 23:43:42 localhost obs-studio_obs-studio.desktop[12529]: #011YUV mode:          601/Partial
Aug 23 23:43:42 localhost obs-studio_obs-studio.desktop[12529]: info: NV12 texture support not available
Aug 23 23:43:42 localhost obs-studio_obs-studio.desktop[12529]: info: Audio monitoring device:
Aug 23 23:43:42 localhost obs-studio_obs-studio.desktop[12529]: #011name: Default
Aug 23 23:43:42 localhost obs-studio_obs-studio.desktop[12529]: #011id: default
Aug 23 23:43:42 localhost obs-studio_obs-studio.desktop[12529]: info: ---------------------------------
Aug 23 23:43:42 localhost obs-studio_obs-studio.desktop[12529]: info: [StreamFX] Loading Version 0.8.3.0-ee225959
Aug 23 23:43:42 localhost obs-studio_obs-studio.desktop[12529]: libpng warning: iCCP: known incorrect sRGB profile
Aug 23 23:43:42 localhost obs-studio_obs-studio.desktop[12529]: libpng warning: iCCP: known incorrect sRGB profile
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info: [StreamFX] Loaded Version 0.8.3.0-ee225959
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: warning: Failed to load 'en-US' text for module: 'decklink-ouput-ui.so'
Aug 23 23:43:43 localhost org.gnome.Shell.desktop[8920]: syntax error: line 1 of stdin
Aug 23 23:43:43 localhost org.gnome.Shell.desktop[8920]: Errors encountered in stdin; not compiled.
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: load_input_helper [1833]: XkbGetKeyboard failed to locate a valid keyboard!
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: libUIOHook: Cross-platfrom userland keyboard and mouse hooking.
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: Copyright (C) 2006-2015 Alexander Barker.  All Rights Received.
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: https://github.com/kwhat/libuiohook/
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: libUIOHook is free software: you can redistribute it and/or modify
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: it under the terms of the GNU Lesser General Public License as published
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: by the Free Software Foundation, either version 3 of the License, or
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: (at your option) any later version.
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: libUIOHook is distributed in the hope that it will be useful,
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: but WITHOUT ANY WARRANTY; without even the implied warranty of
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: GNU General Public License for more details.
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: You should have received a copy of the GNU Lesser General Public License
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: along with this program.  If not, see <http://www.gnu.org/licenses/>.
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info: [pango]: Loaded system fontconfig
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: libDeckLinkAPI.so: cannot open shared object file: No such file or directory
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: warning: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info: No blackmagic support
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info: [obs-browser]: Version 2.8.6
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: error: os_dlopen(libnvidia-encode.so.1->libnvidia-encode.so.1): libnvidia-encode.so.1: cannot open shared object file: No such file or directory
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info: FFMPEG VAAPI supported
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info: [obs-ndi] hello ! (version 4.9.1)
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info: [obs-ndi] Trying ''
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info: [obs-ndi] Trying '/usr/lib'
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info: [obs-ndi] Trying '/usr/local/lib'
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info: [obs-ndi] Found NDI library at '/usr/local/lib/libndi.so.4'
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info: [obs-ndi] NDI runtime loaded successfully
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info: [obs-ndi] NDI library initialized successfully (NDI SDK LINUX 18:32:11 Jun 30 2020 4.5.3)
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: warning: Failed to load 'en-US' text for module: 'obs-vnc.so'
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info: [obs-vnc] plugin loaded successfully (version 0.1.0)
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info: [obs-websocket] you can haz websockets (version 4.8.0)
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info: [obs-websocket] qt version (compile-time): 5.9.5 ; qt version (run-time): 5.9.5
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info: [obs-websocket] module loaded!
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: warning: Failed to load 'en-US' text for module: 'replay-source.so'
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info: VLC found, VLC video source enabled
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info: ---------------------------------
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info:   Loaded Modules:
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info:     vlc-video.so
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info:     v4l2sink.so
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info:     text-freetype2.so
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info:     spectralizer.so
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info:     source-switcher.so
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info:     scrab.so
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info:     rtmp-services.so
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info:     replay-source.so
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info:     obs-x264.so
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info:     obs-websocket.so
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info:     obs-vnc.so
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info:     obs-vintage-filter.so
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info:     obs-transitions.so
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info:     obs-transition-matrix.so
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info:     obs-rgb-levels-filter.so
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info:     obs-outputs.so
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info:     obs-ndi.so
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info:     obs-libfdk.so
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info:     obs-filters.so
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info:     obs-ffmpeg.so
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info:     obs-browser.so
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info:     move-transition.so
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info:     linux-v4l2.so
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info:     linux-pulseaudio.so
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info:     linux-jack.so
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info:     linux-decklink.so
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info:     linux-capture.so
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info:     linux-alsa.so
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info:     libtext-pango.so
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info:     input-overlay.so
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info:     image-source.so
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info:     frontend-tools.so
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info:     freeze-filter.so
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info:     dynamic-delay.so
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info:     dir-watch-media.so
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info:     decklink-ouput-ui.so
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info:     advanced-scene-switcher.so
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info:     StreamFX.so
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info: ---------------------------------
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: error: os_dlopen(../obs-plugins/obs-browser->../obs-plugins/obs-browser.so): ../obs-plugins/obs-browser.so: cannot open shared object file: No such file or directory
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info: ==== Startup complete ===============================================
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: error: Service '' not found
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info: No scene file found, creating default scene
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info: All scene data cleared
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info: ------------------------------------------------
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info: pulse-input: Server name: 'pulseaudio 11.1-rebootstrapped'
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info: pulse-input: Audio format: s16le, 44100 Hz, 2 channels
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info: pulse-input: Started recording from 'alsa_output.pci-0000_03_00.6.analog-stereo.monitor'
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info: pulse-input: Server name: 'pulseaudio 11.1-rebootstrapped'
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info: pulse-input: Audio format: s16le, 44100 Hz, 2 channels
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info: pulse-input: Started recording from 'alsa_input.pci-0000_03_00.6.analog-stereo'
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: info: Switched to scene 'Scene'
Aug 23 23:43:43 localhost obs-studio_obs-studio.desktop[12529]: warning: Failed to glob scene collections
Aug 23 23:43:43 localhost kernel: obs[12529]: segfault at 0 ip 00007f72bddcb162 sp 00007ffe0bdd13c0 error 4 in advanced-scene-switcher.so[7f72bdd44000+b4000]
Aug 23 23:43:43 localhost kernel: Code: 48 8d 35 76 8a 01 00 48 89 df 8b 90 f8 02 00 00 e8 93 29 fa ff 48 8b 45 00 48 8d 35 6c 8a 01 00 48 89 df 48 8b 80 00 03 00 00 <48> 63 10 e8 76 29 fa ff 48 8b 45 00 48 8d 35 5d 8a 01 00 48 89 df
Aug 23 23:43:43 localhost abrt-hook-ccpp[12674]: Process 12529 (obs) of user 1000 killed by SIGSEGV - dumping core
Aug 23 23:43:44 localhost abrt-hook-ccpp[12675]: Can't generate core backtrace: dwfl_getthread_frames failed: Callback returned failure
Aug 23 23:43:44 localhost abrt-hook-ccpp[12674]: Core backtrace generator exited with error 1
Aug 23 23:43:44 localhost abrtd[1239]: Size of '/var/spool/abrt' >= 5000 MB (MaxCrashReportsSize), deleting old directory 'ccpp-2020-08-23-23:42:28-12322'
Aug 23 23:43:44 localhost abrt-server[12676]: Unsupported container technology
Aug 23 23:43:44 localhost abrt-server[12676]: Lock file '.lock' was locked by process 12679, but it crashed?
Aug 23 23:43:45 localhost abrt-server[12676]: /bin/sh: reporter-systemd-journal: command not found
Aug 23 23:45:42 localhost journal[11468]: Window 0x55b83a872650 is a temporary window without parent, application will not be able to position it on screen.
Aug 23 23:45:42 localhost journal[11468]: Window 0x55b83a872650 is a temporary window without parent, application will not be able to position it on screen.
Aug 23 23:45:42 localhost journal[11468]: gdk_wayland_window_handle_configure_popup: assertion 'impl->transient_for' failed
Aug 23 23:46:00 localhost systemd[1]: Starting Cleanup of Temporary Directories...
Aug 23 23:46:00 localhost systemd-tmpfiles[12800]: [/usr/lib/tmpfiles.d/dovecot.conf:1] Line references path below legacy directory /var/run/, updating /var/run/dovecot → /run/dovecot; please update the tmpfiles.d/ drop-in file accordingly.
Aug 23 23:46:00 localhost systemd-tmpfiles[12800]: [/usr/lib/tmpfiles.d/pesign.conf:1] Line references path below legacy directory /var/run/, updating /var/run/pesign → /run/pesign; please update the tmpfiles.d/ drop-in file accordingly.
Aug 23 23:46:00 localhost systemd-tmpfiles[12800]: [/usr/lib/tmpfiles.d/subscription-manager.conf:1] Line references path below legacy directory /var/run/, updating /var/run/rhsm → /run/rhsm; please update the tmpfiles.d/ drop-in file accordingly.
Aug 23 23:46:00 localhost systemd-tmpfiles[12800]: [/usr/lib/tmpfiles.d/tog-pegasus.conf:1] Line references path below legacy directory /var/run/, updating /var/run/tog-pegasus → /run/tog-pegasus; please update the tmpfiles.d/ drop-in file accordingly.
Aug 23 23:46:02 localhost systemd[1]: Started Cleanup of Temporary Directories.
^Z
[2]+  Stopped                 tail -f messages

**Comment by eduardocf22** [comment]
Please
Your comments and advice
I appreciate it
Thanks

**Comment by flexiondotorg** [comment]
It looks like you are using Wayland? Have you tried X11?

**Comment by eduardocf22** [comment]
Thanks for your comments
 Have you tried X11? No
Please your advice (the step by step for centos 8)
Br

**Comment by flexiondotorg** [comment]
My advice is to try using X11.

**Comment by eduardocf22** [comment]
OBS-Studio removed, the best solution.
Ok...Thanks.

**Comment by eduardocf22** [comment]
OK, please let me know.
I need to fix this error. I will appreciate it.

**Comment by eduardocf22** [comment]
Chech the error using root
[root@localhost ~]# obs-studio
No protocol specified
qt.qpa.screen: QXcbConnection: Could not connect to display :0.0
Could not connect to any X display.
[root@localhost ~]#

**Comment by eduardocf22** [comment]
more details below
obs-studio
QSocketNotifier: Can only be used with threads started with QThread
Using Wayland-EGL
/usr/share/libdrm/amdgpu.ids: No such file or directory
Attempted path: share/obs/obs-studio/locale/en-US.ini
Attempted path: /usr/share/obs/obs-studio/locale/en-US.ini
Attempted path: share/obs/obs-studio/themes/Dark.qss
Attempted path: /usr/share/obs/obs-studio/themes/Dark.qss
info: CPU Name: AMD Ryzen 3 3200U with Radeon Vega Mobile Gfx
info: CPU Speed: 3025.257MHz
info: Physical Cores: 2, Logical Cores: 4
info: Physical Memory: 5667MB Total, 470MB Free
info: Kernel Version: Linux 4.18.0-193.14.2.el8_2.x86_64
info: Distribution: "Ubuntu Core" "18"
info: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.20.6
info: Portable mode: false
Attempted path: share/obs/obs-studio/themes/Dark/no_sources.svg
Attempted path: /usr/share/obs/obs-studio/themes/Dark/no_sources.svg
QMetaObject::connectSlotsByName: No matching signal for on_advAudioProps_clicked()
QMetaObject::connectSlotsByName: No matching signal for on_advAudioProps_destroyed()
QMetaObject::connectSlotsByName: No matching signal for on_actionGridMode_triggered()
QMetaObject::connectSlotsByName: No matching signal for on_program_customContextMenuRequested(QPoint)
info: OBS 25.0.8-modified (linux)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
	samples per sec: 44100
	speakers:        2
info: ---------------------------------
info: Initializing OpenGL...
info: Loading up OpenGL on adapter X.Org AMD RAVEN2 (DRM 3.33.0, 4.18.0-193.14.2.el8_2.x86_64, LLVM 10.0.0)
info: OpenGL loaded successfully, version 4.6 (Core Profile) Mesa 20.0.8, shading language 4.60
info: ---------------------------------
info: video settings reset:
	base resolution:   1366x768
	output resolution: 1092x614
	downscale filter:  Bicubic
	fps:               30/1
	format:            NV12
	YUV mode:          601/Partial
info: NV12 texture support not available
info: Audio monitoring device:
	name: Default
	id: default
info: ---------------------------------
info: [StreamFX] Loading Version 0.8.3.0-ee225959
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
info: [StreamFX] Loaded Version 0.8.3.0-ee225959
warning: Failed to load 'en-US' text for module: 'decklink-ouput-ui.so'
libUIOHook: Cross-platfrom userland keyboard and mouse hooking.
Copyright (C) 2006-2015 Alexander Barker.  All Rights Received.
https://github.com/kwhat/libuiohook/

libUIOHook is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

libUIOHook is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

load_input_helper [1833]: XkbGetKeyboard failed to locate a valid keyboard!
info: [pango]: Loaded system fontconfig
libDeckLinkAPI.so: cannot open shared object file: No such file or directory
warning: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
info: No blackmagic support
info: [obs-browser]: Version 2.8.6
error: os_dlopen(libnvidia-encode.so.1->libnvidia-encode.so.1): libnvidia-encode.so.1: cannot open shared object file: No such file or directory

info: FFMPEG VAAPI supported
info: [obs-ndi] hello ! (version 4.9.1)
info: [obs-ndi] Trying ''
info: [obs-ndi] Trying '/usr/lib'
info: [obs-ndi] Trying '/usr/local/lib'
info: [obs-ndi] Found NDI library at '/usr/local/lib/libndi.so.4'
info: [obs-ndi] NDI runtime loaded successfully
info: [obs-ndi] NDI library initialized successfully (NDI SDK LINUX 18:32:11 Jun 30 2020 4.5.3)
warning: Failed to load 'en-US' text for module: 'obs-vnc.so'
info: [obs-vnc] plugin loaded successfully (version 0.1.0)
info: [obs-websocket] you can haz websockets (version 4.8.0)
info: [obs-websocket] qt version (compile-time): 5.9.5 ; qt version (run-time): 5.9.5
info: [obs-websocket] module loaded!
warning: Failed to load 'en-US' text for module: 'replay-source.so'
info: VLC found, VLC video source enabled
info: ---------------------------------
info:   Loaded Modules:
info:     vlc-video.so
info:     v4l2sink.so
info:     text-freetype2.so
info:     spectralizer.so
info:     source-switcher.so
info:     scrab.so
info:     rtmp-services.so
info:     replay-source.so
info:     obs-x264.so
info:     obs-websocket.so
info:     obs-vnc.so
info:     obs-vintage-filter.so
info:     obs-transitions.so
info:     obs-transition-matrix.so
info:     obs-rgb-levels-filter.so
info:     obs-outputs.so
info:     obs-ndi.so
info:     obs-libfdk.so
info:     obs-filters.so
info:     obs-ffmpeg.so
info:     obs-browser.so
info:     move-transition.so
info:     linux-v4l2.so
info:     linux-pulseaudio.so
info:     linux-jack.so
info:     linux-decklink.so
info:     linux-capture.so
info:     linux-alsa.so
info:     libtext-pango.so
info:     input-overlay.so
info:     image-source.so
info:     frontend-tools.so
info:     freeze-filter.so
info:     dynamic-delay.so
info:     dir-watch-media.so
info:     decklink-ouput-ui.so
info:     advanced-scene-switcher.so
info:     StreamFX.so
info: ---------------------------------
error: os_dlopen(../obs-plugins/obs-browser->../obs-plugins/obs-browser.so): ../obs-plugins/obs-browser.so: cannot open shared object file: No such file or directory

info: ==== Startup complete ===============================================
error: Service '' not found
info: No scene file found, creating default scene
info: All scene data cleared
info: ------------------------------------------------
info: pulse-input: Server name: 'pulseaudio 11.1-rebootstrapped'
info: pulse-input: Audio format: s16le, 44100 Hz, 2 channels
info: pulse-input: Started recording from 'alsa_output.pci-0000_03_00.6.analog-stereo.monitor'
info: pulse-input: Server name: 'pulseaudio 11.1-rebootstrapped'
info: pulse-input: Audio format: s16le, 44100 Hz, 2 channels
info: pulse-input: Started recording from 'alsa_input.pci-0000_03_00.6.analog-stereo'
info: Switched to scene 'Scene'
warning: Failed to glob scene collections
Segmentation fault (core dumped)

**Comment by eduardocf22** [comment]
Im Using Wayland
please, your comments,
I need to fix this error.

**Comment by flexiondotorg** [comment]
Please see issue #50 

Upstream OBS Studio is still working on implementing Wayland support.
