### ISSUE TITLE
vaapi driver issue

### ISSUE THREAD

**Issue by takov751** [snapcrafters/obs-studio#85]
Greetings ,big fan of the project. However i have stumbled upon a problem.
My system used the iHD vaapi driver which missing from the obs-studio snap of course due its non-free nature (i presume),however When i start obs-studio it wants to use the iris driver which would never work with my UHD620 card, when i remove the non-free driver and i fall back i965 obs-studio still  want to use iris driver and when i used 
```
LIBVA_DRIVER_NAME=i965 obs-studio.vainfo 
libva info: VA-API version 1.1.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'i965'
libva info: Trying to open /snap/obs-studio/1143/usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so

```

as in the snap the driver called i965_dri.so . Do you have any idea what could be my problem or is this even a bug?
Thank you in advance

**Comment by popey** [comment]
Looks like the iHD vaapi driver is available at https://github.com/intel/media-driver and so could well be integrated, potentially :D

**Comment by takov751** [comment]
That would be great to include that driver as well , however my take on this so far that the snap for some reason detects the wrong gpu driver and changing that variable breaks it because the naming of the driver files somewhat hard coded

**Comment by flexiondotorg** [comment]
Fixed via https://github.com/snapcrafters/obs-studio/pull/88
