### ISSUE TITLE
Driver Issue?

### ISSUE THREAD

**Issue by davidjsullivan8** [snapcrafters/obs-studio#86]
All,
I'm very new to Ubuntu.  I have this old laptop that I loaded Ubuntu.  OBS would not work.  Driver issue.  I loaded Windows 10 on the machine.  No issue - OBS ran fine.  Over loaded my CPU, but I need to add more RAM.  Anyway, my issue is that after loading Ubuntu now as a dual boot, still getting the same error as before.  Thoughts please on how to resolve?  Details:
davidjsullivan8@davidjsullivan8-Studio-1537:~$ snap run obs-studio
Attempted path: share/obs/obs-studio/locale/en-US.ini
Attempted path: /usr/share/obs/obs-studio/locale/en-US.ini
Attempted path: share/obs/obs-studio/themes/Dark.qss
Attempted path: /usr/share/obs/obs-studio/themes/Dark.qss
info: CPU Name: Intel(R) Core(TM)2 Duo CPU     T6400  @ 2.00GHz
info: CPU Speed: 1516.413MHz
info: Physical Cores: 2, Logical Cores: 2
info: Physical Memory: 3895MB Total, 370MB Free
info: Kernel Version: Linux 5.4.0-52-generic
info: Distribution: "Ubuntu Core" "18"
info: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.20.8
info: Portable mode: false
Attempted path: share/obs/obs-studio/themes/Dark/no_sources.svg
Attempted path: /usr/share/obs/obs-studio/themes/Dark/no_sources.svg
QMetaObject::connectSlotsByName: No matching signal for on_advAudioProps_clicked()
QMetaObject::connectSlotsByName: No matching signal for on_advAudioProps_destroyed()
QMetaObject::connectSlotsByName: No matching signal for on_actionGridMode_triggered()
QMetaObject::connectSlotsByName: No matching signal for on_program_customContextMenuRequested(QPoint)
QMetaObject::connectSlotsByName: No matching signal for on_transitionRemove_clicked()
info: OBS 26.0.2-modified (linux)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
	samples per sec: 48000
	speakers:        2
info: ---------------------------------
info: Initializing OpenGL...
error: X Error: GLXBadFBConfig, Major opcode: 152, Minor opcode: 34, Serial: 29
error: Failed to create OpenGL context.
error: Failed to create context!
error: device_create (GL) failed
error: Failed to initialize video.  Your GPU may not be supported, or your graphics drivers may need to be updated.
info: Freeing OBS context data
info: == Profiler Results =============================
info: run_program_init: 8486.15 ms
info:  ┣OBSApp::AppInit: 9.317 ms
info:  ┃ ┗OBSApp::InitLocale: 3.445 ms
info:  ┗OBSApp::OBSInit: 161.289 ms
info:    ┣obs_startup: 24.258 ms
info:    ┗OBSBasic::OBSInit: 49.933 ms
info:      ┣OBSBasic::InitBasicConfig: 0.284 ms
info:      ┣OBSBasic::ResetAudio: 0.382 ms
info:      ┗OBSBasic::ResetVideo: 49.138 ms
info: obs_hotkey_thread(25 ms): min=0.158 ms, median=0.444 ms, max=18.836 ms, 99th percentile=10.397 ms, 100% below 25 ms
info: audio_thread(Audio): min=0.006 ms, median=0.08 ms, max=0.193 ms, 99th percentile=0.128 ms
info: =================================================
info: == Profiler Time Between Calls ==================
info: obs_hotkey_thread(25 ms): min=25.252 ms, median=25.655 ms, max=43.961 ms, 14.7651% within ±2% of 25 ms (0% lower, 85.2349% higher)
info: =================================================
info: Number of memory leaks: 178

**Comment by popey** [comment]
Thanks for the issue report. I don't have a sufficiently aged computer to reproduce this issue I'm afraid. Even if you did get OBS working on it, I'd imagine it would be pretty painful. That's a super old computer to be running something like that on, even if it does work on Windows.

**Comment by flexiondotorg** [comment]
Please refresh the OBS snap (`snap refresh obs-sudio`) and make sure you have revision 1157 (`snap info obs-studio)` as this issue may have been fixed via #88. Let us know.

**Comment by flexiondotorg** [comment]
That said, OBS on Windows uses DirectX where as Linux uses OpenGL 3.3 as a minimum requirement. Your hardware pre-dates the introduction of OpenGL 3.3 and therefore running OBS on Linux is not an option for you. Sorry.

**Comment by davidjsullivan8** [comment]
Thanks for the help.  Much appreciated.  Totally understand working with an ancient machine is not ideal.  Gotta work with what you have.  I ran scripts offered here and in other referenced threads.  Here's a summary of the terminal response in case you are interested:
davidjsullivan8@davidjsullivan8-Studio-1537:~$ sudo refresh obs-studio
[sudo] password for davidjsullivan8: 
sudo: refresh: command not found
davidjsullivan8@davidjsullivan8-Studio-1537:~$ snap refresh obs-sudio
snap "obs-sudio" is not installed
davidjsullivan8@davidjsullivan8-Studio-1537:~$ sudo refresh obs-studio
sudo: refresh: command not found
davidjsullivan8@davidjsullivan8-Studio-1537:~$ snap info obs-studio
name:      obs-studio
summary:   OBS Studio for live streaming and screen recording
publisher: Snapcrafters
store-url: https://snapcraft.io/obs-studio
contact:   https://github.com/snapcrafters/obs-studio/issues
license:   GPL-2.0
snap-id:      6uLU2MJmBURfLNz4rmL4WT2CmtVULE2u
tracking:     latest/stable
refresh-date: 5 days ago, at 13:43 EST
channels:
  latest/stable:    26.0.2 2020-11-08 (1157) 212MB -
  latest/candidate: ↑                              
  latest/beta:      ↑                              
  latest/edge:      26.0.2 2020-11-08 (1158) 212MB -
installed:          26.0.2            (1141) 189MB -
