### ISSUE TITLE
OBS Studio v4l2 output can't be selected in Zoom

### ISSUE THREAD

**Issue by janakelarsson** [snapcrafters/obs-studio#89]
From this weekend I cannot use OBS Studio virtual output in Zoom. This used to work. 

Only thing changed I believe is a snap refresh.

**Comment by stijnghesquiere** [comment]
OBS virtual output does no longer work in Ubuntu 20.04 for Microsoft Teams, Skype and zoom. The virtual camera simply doesn't show up anymore in the list of camera's. 
It does work for discord however.... 
It did work last week, not anymore after an update?

**Comment by janakelarsson** [comment]
Yes, it did work before the update.

**Comment by stijnghesquiere** [comment]
My preview in OBS itself doesn't work after the update... Looks like several things have changed.

**Comment by janakelarsson** [comment]
My preview works, but is more jittery. On the plus side, the processor load is much lower.

**Comment by Alex-INtegrator** [comment]
Hi,
I just did a fresh upgrade to Ubuntu 20.04 (Linux Mint 20 - Cinnamon 4.6.7), then followed installation instructions on https://snapcraft.io/obs-studio,  and even if preview and full OBS seems to work without problems, there is no option to select VirtualCam output on Zoom.

**Comment by janakelarsson** [comment]
I assume you installed v4l2loopback-dkms, loaded the kernel module, and started Tools->V4L2 Video Output?

**Comment by Alex-INtegrator** [comment]
Yes, I did!.

**Comment by janakelarsson** [comment]
You can test if v4l2loopback works by trying `ffplay /dev/video99`

**Comment by Alex-INtegrator** [comment]
Thanks for this hint. Yes `/dev/video99` works using `ffplay` . I am wondering if that could be a Zoom imcompatibility. Using Zoom (5.4.2 (53391.1108)). Released on 9th november 20

**Comment by Alex-INtegrator** [comment]
I just tried VLC to test /dev/video99 without success. 
![image](https://user-images.githubusercontent.com/11395288/98729246-a06cfc00-2368-11eb-8cf5-43ca4624c636.png)

**Comment by janakelarsson** [comment]
Correct, VLC can play from the camera but not from v4l2loopback from OBS studio. Console tells me "not a video capture device"

**Comment by stijnghesquiere** [comment]
It comes from upstream: 
https://obsproject.com/forum/threads/video-capture-device-v4l2-plugin.17358/page-4
Same problem with OBS V4L2loopback not visible in zoom etc.

**Comment by stijnghesquiere** [comment]
So basically I see this: 

Skype: no, virtual camera not selectable/visible
Zoom: no, virtual camera not selectable/visible
Teams: no, virtual camera not selectable/visible
VLC: no
Discord: yes, working V4L2loopback!

**Comment by janakelarsson** [comment]
Seems there was a regression in the v4l2loopback package. There is an update from yesterday mentioned at https://www.ubuntuupdates.org/package/core/focal/universe/proposed/v4l2loopback that has yet to make it to the update servers. I installed it by enabling "proposed" packages in ubuntu package manager, and now the device works.

Strangely I can't seem to be able to use /dev/video0, but /dev/video1 does work. Probably something else.

**Comment by janakelarsson** [comment]
See https://bugs.launchpad.net/ubuntu/+source/v4l2loopback/+bug/1901491
