### ISSUE TITLE
v4l2loopback / v4l2loopback_dc dont get recognized in Arch and Manjaro

### ISSUE THREAD

**Issue by nevermore2k** [snapcrafters/obs-studio#91]
On Fedora and Ubuntu based Distrobutions they work just fine. On Arch based systems they dont get recognized by OBS-Studio Snap Edition. I activated all permissions.  What do i miss ? 
![image](https://user-images.githubusercontent.com/5654905/101661102-2bb0de80-3a48-11eb-941c-6800fbaf07aa.png)

**Comment by flexiondotorg** [comment]
Duplicate of #91

**Comment by Kr1ss-XD** [comment]
> Duplicate of #91

You might've closed this by mistake @flexiondotorg - this **is** #91 :wink:
