### ISSUE TITLE
Latest OBS no longer detect v4l2loopback device

### ISSUE THREAD

**Issue by tuapuikia** [snapcrafters/obs-studio#92]
The latest version of OBS had changed the way to detect and store the webcam information. By default, it will search for any real USB webcam device symlinked to /dev/v4l/by-path/

Issue: v4l2loopback device is not detected
Solution: Use udev to automatically add the symlink to /dev/v4l/by-path

cat /etc/udev/rules.d/60-persistent-v4l2loopback.rules
`
KERNEL=="video*", ATTR{max_openers}=="?*", SYMLINK+="v4l/by-path/v4l2loopback-$attr{name}-video"
`

Run udevadm to create the missing symlink or reboot the machine.
`
sudo udevadm trigger -v -s video4linux
`

**Comment by nevermore2k** [comment]
hm i did the  sudo udevadm trigger -v -s video4linux. and there are still no v4l2loopback devices recognized by OBS. 
here is the output
sudo udevadm trigger -v -s video4linux               
/sys/devices/pci0000:00/0000:00:07.1/0000:0e:00.3/usb3/3-2/3-2:1.0/video4linux/video3
/sys/devices/pci0000:00/0000:00:07.1/0000:0e:00.3/usb3/3-2/3-2:1.0/video4linux/video4
/sys/devices/pci0000:00/0000:00:07.1/0000:0e:00.3/usb4/4-4/4-4.3/4-4.3:1.0/video4linux/video1
/sys/devices/pci0000:00/0000:00:07.1/0000:0e:00.3/usb4/4-4/4-4.3/4-4.3:1.0/video4linux/video2
/sys/devices/virtual/video4linux/video0
/sys/devices/virtual/video4linux/video10
/sys/devices/virtual/video4linux/video11
/sys/devices/virtual/video4linux/video12

there is no 60-persistent-v4l2loopback.rules files on the System ( manjaro and feodora)

i realy dont have a clue what to do here.

**Comment by tuapuikia** [comment]
> hm i did the sudo udevadm trigger -v -s video4linux. and there are still no v4l2loopback devices recognized by OBS.
> here is the output
> sudo udevadm trigger -v -s video4linux
> /sys/devices/pci0000:00/0000:00:07.1/0000:0e:00.3/usb3/3-2/3-2:1.0/video4linux/video3
> /sys/devices/pci0000:00/0000:00:07.1/0000:0e:00.3/usb3/3-2/3-2:1.0/video4linux/video4
> /sys/devices/pci0000:00/0000:00:07.1/0000:0e:00.3/usb4/4-4/4-4.3/4-4.3:1.0/video4linux/video1
> /sys/devices/pci0000:00/0000:00:07.1/0000:0e:00.3/usb4/4-4/4-4.3/4-4.3:1.0/video4linux/video2
> /sys/devices/virtual/video4linux/video0
> /sys/devices/virtual/video4linux/video10
> /sys/devices/virtual/video4linux/video11
> /sys/devices/virtual/video4linux/video12
> 
> there is no 60-persistent-v4l2loopback.rules files on the System ( manjaro and feodora)
> 
> i realy dont have a clue what to do here.

You need to create the udev rule manually.
`
echo "KERNEL=="video*", ATTR{max_openers}=="?*", SYMLINK+="v4l/by-path/v4l2loopback-$attr{name}-video"" | sudo tee /etc/udev/rules.d/60-persistent-v4l2loopback.rules
`

**Comment by nevermore2k** [comment]
Thank you !

**Comment by flexiondotorg** [comment]
I can't reproduce this issue. The built-in Virtual Camera in OBS (new in 26.1.0 for Linux) works correctly with the need to create new udev rules. I am working on a patch for snapd to improve camera device support, include v4l2loopback devices, which is being tracked here:

  * https://github.com/snapcrafters/obs-studio/issues/40
  * https://github.com/snapcore/snapd/pull/9734
