### ISSUE TITLE
Version 26.1.0 released, but latest snap is 26.0.2

### ISSUE THREAD

**Issue by fcole90** [snapcrafters/obs-studio#93]
The latest release is available for all platforms, but not using snap.

Is there any CI/CD in place that takes care of new releases?

**Comment by popey** [comment]
We're aware. But each release brings new and interesting problems. I believe @flexiondotorg is looking into it.

**Comment by fcole90** [comment]
I'm sorry to hear that's so hard, but I'm glad someone is working on it

**Comment by fcole90** [comment]
Great job! :smiley:  when do you think we can find it on the store? :blush:
