### ISSUE TITLE
Please update the snap to the latest OBS release

### ISSUE THREAD

**Issue by KristijanZic** [snapcrafters/obs-studio#94]
OBS 26.1 is released and brings in quite a few new features for Linux:
https://github.com/obsproject/obs-studio/releases

**Comment by popey** [comment]
See https://github.com/snapcrafters/obs-studio/issues/93

**Comment by KristijanZic** [comment]
Wow, that was fast :+1:

**Comment by KristijanZic** [comment]
When will it land in the store?

**Comment by KristijanZic** [comment]
Just got the update, thank you so much!
