### ISSUE TITLE
obs snap not working with droidcam obs pluggin through usb

### ISSUE THREAD

**Issue by exisoft** [snapcrafters/obs-studio#96]
The OBS snap version is not allowing access to my phone camera through usb using the droidcam app/pluggin. It works well with wifi, but the phone will not show up in available devices when [refresh device list] is pressed. This function works perfectly when used in the OBS version (25.0.3) available through the repo. I allowed every available permission for the snap but they did not change the outcome.

**Comment by flexiondotorg** [comment]
Please try connecting the raw-usb interface:

    snap connect obs-studio:raw-usb

**Comment by JGs99** [comment]
Does obs.ninja support USB connections? I cant find the details, it does not look like it.
